"""G2a report: benign baseline on the pre-registered MAWI slices -> docs/results_g2a.md.

Reads results/g2/a_*.npz (from ``g2_mawi.py``). Per (day, gate, hash arm): the draw is the unit, intervals are
percentile bootstraps over draws. Definitions follow docs/preregistration.md (G1b amendments, G2a entry).
"""

from __future__ import annotations

import glob
import re
from pathlib import Path

import numpy as np
import pandas as pd

from dgrade.flowstats import FlowIndex, downgraded_flows
from dgrade.netbeacon_sim import (
    FALLBACK_COLLISION,
    FALLBACK_EMPTY,
    MEMO,
    NEW_OWNER,
    flow_ids,
)

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "results/g2"
DAYS = {"p": "2022-09-14 (primary)", "r": "2023-03-15 (replication)"}
ARMS = {"crc": "unkeyed CRC, clock varied", "polyirr": "irreducible polynomial, clock fixed at grid 0"}
PAT = re.compile(r"a_([pr])_(model|oracle)_(crc|polyirr)(?:_(\d+))?_at(\d+)\.npz")


def ci(x: np.ndarray, n=4000, seed=0) -> tuple[float, float]:
    rng = np.random.default_rng(seed)
    m = np.array([rng.choice(x, len(x)).mean() for _ in range(n)])
    return float(np.percentile(m, 2.5)), float(np.percentile(m, 97.5))


def cell(d: pd.DataFrame, col: str, pct: bool = True) -> str:
    lo, hi = ci(d[col].to_numpy())
    f = (lambda v: f"{v:.3%}") if pct else (lambda v: f"{v:,.0f}")
    return f"{f(d[col].mean())} [{f(lo)}, {f(hi)}]"


def main() -> None:
    idx = {}
    for d in DAYS:
        pk = np.load(OUT / f"stream_{d}.npy")
        idx[d] = FlowIndex(flow_ids(pk, 1 << 62))
    rows = []
    for path in sorted(glob.glob(str(OUT / "a_*.npz"))):
        m = PAT.match(Path(path).name)
        if not m:
            continue
        day, gate, kind, seed, g = m.group(1), m.group(2), m.group(3), m.group(4), int(m.group(5))
        oc = np.load(path)["outcome"]
        flag = downgraded_flows(oc, idx[day])
        n = len(oc)
        rows.append({"day": day, "gate": gate, "kind": kind, "seed": None if seed is None else int(seed), "grid": g,
                     "flows_down_share": float(flag.mean()), "pkts_down_share": float(flag[idx[day].code].mean()),
                     "collision_share": float(np.mean(oc == FALLBACK_COLLISION)),
                     "empty_share": float(np.mean(oc == FALLBACK_EMPTY)),
                     "takeovers": int(np.sum(oc == NEW_OWNER)), "memo_share": float(np.mean(oc == MEMO)),
                     "flows": idx[day].n_flows, "packets": n})
    df = pd.DataFrame(rows)
    df.to_csv(OUT / "g2a_summary.csv", index=False)
    L = ["# G2a results: NetBeacon slot behaviour on MAWI, no attacker", "",
         ("Generated by `scripts/g2a_report.py` from `results/g2/a_*.npz`. First 120 s of the pre-registered days, "
          "65,536 slots, NetBeacon's timeout. `model` = the shipped PeerRush-trained flow-size gate; `oracle` = a flow "
          "takes a slot iff it truly has more than 50 packets in the slice. MAWI has no application labels, so this "
          "measures slot contention, not accuracy. A packet is a *collision* when an active slot holder refuses its "
          "flow; an *empty-slot refusal* is the clock-wrap artefact (a never-used slot looks active for 268 ms after "
          "each 4.295 s wrap). 95% intervals are percentile bootstraps over draws."), ""]
    for day, dname in DAYS.items():
        L += [f"## {dname}", "", ("| gate | arm | draws | downgraded flows (share of flows) | downgraded packets (share) | "
              "collision packets (share) | empty-slot refusals (share) | takeovers | memo packets (share) |"),
              "|---|---|---|---|---|---|---|---|---|"]
        for gate in ("model", "oracle"):
            for kind, aname in ARMS.items():
                d = df[(df.day == day) & (df.gate == gate) & (df.kind == kind)]
                if kind == "polyirr":
                    d = d[d.grid == 0]
                if not len(d):
                    continue

                L.append(f"| {gate} | {aname} | {len(d)} | {cell(d, 'flows_down_share')} | {cell(d, 'pkts_down_share')} | "
                         f"{cell(d, 'collision_share')} | {cell(d, 'empty_share')} | {cell(d, 'takeovers', False)} | "
                         f"{cell(d, 'memo_share')} |")
        L.append("")
    L += ["## Keyed against unkeyed at the same clock (grid 0)", "",
          ("The fixed-clock keyed arm runs at clock grid 0, where the trace starts on a wrap boundary, so its empty-slot "
           "share is not comparable with the clock-varied average. This table compares like with like: the single unkeyed "
           "run at grid 0 against the 30 keyed draws at grid 0."), "",
          ("| day | gate | unkeyed at grid 0: downgraded packets | keyed draws: median [min, max] | keyed draws at or below unkeyed | "
          "unkeyed at grid 0: collisions / empty refusals | keyed median: collisions / empty refusals |"), "|---|---|---|---|---|---|---|"]
    for day, dname in DAYS.items():
        for gate in ("oracle", "model"):
            u = df[(df.day == day) & (df.gate == gate) & (df.kind == "crc") & (df.grid == 0)]
            k = df[(df.day == day) & (df.gate == gate) & (df.kind == "polyirr") & (df.grid == 0)]
            if not len(u) or not len(k):
                continue
            u = u.iloc[0]
            L.append(f"| {dname} | {gate} | {u.pkts_down_share:.3%} | {k.pkts_down_share.median():.3%} "
                     f"[{k.pkts_down_share.min():.3%}, {k.pkts_down_share.max():.3%}] | "
                     f"{int((k.pkts_down_share <= u.pkts_down_share).sum())} of {len(k)} | "
                     f"{u.collision_share:.3%} / {u.empty_share:.3%} | "
                     f"{k.collision_share.median():.3%} / {k.empty_share.median():.3%} |")
    L.append("")
    (ROOT / "docs/results_g2a.md").write_text("\n".join(L) + "\n")
    print("\n".join(L))


if __name__ == "__main__":
    main()
