"""G2b targeted-arm report -> docs/results_g2b_targeted.md (docs/preregistration.md, G2b targeted-arm entry).

Per run: victims displaced (downgraded in the attack run and not in the paired no-attack run, out of 20), victim
packets answered off the stored state (not OWNER, NEW_OWNER or MEMO) in excess of the paired baseline, and the
attacker's packets. H2 = victims displaced per attacker packet, K1 over B0-L at the same number of holders.
"""

from __future__ import annotations

import glob
import re
from pathlib import Path

import numpy as np
import pandas as pd

from dgrade.flowstats import FlowIndex, downgraded_flows

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "results/g2"
PAT = re.compile(r"t_([pr])_(top|vul)_(preempt|reactive|b0l|k0)(?:_(\d+))?_at(\d+)\.npz")
DAYS = {"p": "2022-09-14 (primary)", "r": "2023-03-15 (replication)"}
STORED = (0, 1, 2)          # MEMO, OWNER, NEW_OWNER: answered by the full model's state


def boot_ratio(num: np.ndarray, den: np.ndarray, n=4000, seed=0) -> tuple[float, float, float]:
    rng = np.random.default_rng(seed)
    idx = rng.integers(0, len(num), (n, len(num)))
    r = num[idx].mean(axis=1) / np.maximum(den[idx].mean(axis=1), 1e-12)
    return float(num.mean() / max(den.mean(), 1e-12)), float(np.percentile(r, 2.5)), float(np.percentile(r, 97.5))


def main() -> None:
    idxs, base = {}, {}
    rows = []
    for path in sorted(glob.glob(str(OUT / "t_*.npz"))):
        m = PAT.match(Path(path).name)
        if not m:
            continue
        day, vset, arm, h, g = m.group(1), m.group(2), m.group(3), m.group(4), int(m.group(5))
        if day not in idxs:
            idxs[day] = FlowIndex(np.load(OUT / f"targeted_prep_{day}.npz")["code"])
        idx = idxs[day]
        z = np.load(path)
        vic = z["victim_flow"]
        bname = f"a_{day}_oracle_polyirr_{g}_at{g}.npz" if arm == "k0" else f"a_{day}_oracle_crc_at{g}.npz"
        if bname not in base:
            base[bname] = np.load(OUT / bname)["outcome"]
        oc_b, oc_a = base[bname], z["benign_outcome"]
        flag_b, flag_a = downgraded_flows(oc_b, idx), downgraded_flows(oc_a, idx)
        in_v = np.isin(idx.code, vic)
        off_a = in_v & ~np.isin(oc_a, STORED)
        off_b = in_v & ~np.isin(oc_b, STORED)
        rows.append({"day": day, "vset": vset, "arm": arm, "h": int(h) if h else 20, "g": g,
                     "displaced": int((flag_a[vic] & ~flag_b[vic]).sum()),
                     "excess_victim_pkts": int(off_a.sum()) - int(off_b.sum()), "victim_pkts": int(in_v.sum()),
                     "attacker_packets": int(z["n_attacker_packets"]), "holders": int(z["n_holders"]),
                     "failed": int(z["failed"])})
    df = pd.DataFrame(rows)
    df.to_csv(OUT / "g2b_targeted_summary.csv", index=False)
    L = ["# G2b targeted displacement on MAWI (oracle gate)", "",
         ("Generated by `scripts/g2b_targeted_report.py` from `results/g2/t_*.npz`. Analytical abstraction (see "
          "`dgrade.inject_targeted`): K1 holders are given the victim's slot (preempt: before the victim's first "
          "packet; reactive: inside its first inter-packet gap over 300 ms); b0l:H holders land on random slots with the "
          "unkeyed benign hash; k0:H holders land on random slots with the benign hash keyed by an irreducible "
          "polynomial. *Victims displaced* counts victims downgraded in the attack run and not in the paired "
          "no-attack run, out of 20. Victim sets: top = the 20 largest benign long flows, vul = the 20 largest that "
          "never reach 2048 packets."), ""]
    for day, dname in DAYS.items():
        d = df[df.day == day]
        if not len(d):
            continue
        L += [f"## {dname}", "", ("| victims | arm | holders | draws | attacker packets | victims displaced (of 20) | "
              "victim packets moved off stored state (share of victim packets) | displaced per attacker packet ×10⁶ |"),
              "|---|---|---|---|---|---|---|---|"]
        for vset in ("top", "vul"):
            for arm, hs in (("preempt", [20]), ("reactive", [20]), ("b0l", [20, 200, 2000, 20000]),
                            ("k0", [20, 200, 2000, 20000])):
                for h in hs:
                    x = d[(d.vset == vset) & (d.arm == arm) & (d.h == h if arm in ("b0l", "k0") else True)]
                    if not len(x):
                        continue
                    r = x.displaced.mean() / max(x.attacker_packets.mean(), 1) * 1e6
                    L.append(f"| {vset} | {arm} | {x.holders.mean():,.0f} | {len(x)} | {x.attacker_packets.mean():,.0f} | "
                             f"{x.displaced.mean():.2f} | {(x.excess_victim_pkts / x.victim_pkts).mean():.2%} | {r:.1f} |")
        L.append("")
        for vset in ("top", "vul"):
            k1 = d[(d.vset == vset) & (d.arm == "preempt")]
            b0 = d[(d.vset == vset) & (d.arm == "b0l") & (d.h == 20)]
            if len(k1) and len(b0):
                rr = boot_ratio(k1.displaced.to_numpy(float) / k1.attacker_packets.to_numpy(float),
                                b0.displaced.to_numpy(float) / b0.attacker_packets.to_numpy(float))
                L.append(f"- H2 ({dname}, victims {vset}): K1-preempt over B0-L (20 holders): ratio {rr[0]:.1f} "
                         f"[{rr[1]:.1f}, {rr[2]:.1f}] over {len(k1)} and {len(b0)} draws.")
        L.append("")
    (ROOT / "docs/results_g2b_targeted.md").write_text("\n".join(L) + "\n")
    print("\n".join(L))


if __name__ == "__main__":
    main()
