"""G2b fill-arm report -> docs/results_g2b_fill.md (docs/preregistration.md, G2b entry).

Excess = benign flows (and packets) downgraded in the attack run minus the paired no-attack run at the same clock
and hash (the G2a run: unkeyed for k1 and b0l, the keyed run at its own clock for k0). Amplification = excess benign
flows per attacker packet. H2 compares k1 with the decision baseline b0l; the bootstrap unit is the draw.
"""

from __future__ import annotations

import glob
import re
from pathlib import Path

import numpy as np
import pandas as pd

from dgrade.flowstats import FlowIndex, downgraded_flows
from dgrade.netbeacon_sim import flow_ids

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "results/g2"
PAT = re.compile(r"b_([pr])_(oracle|model)_(k1|b0l|k0)_(\d+)_at(\d+)\.npz")
DAYS = {"p": "2022-09-14 (primary)", "r": "2023-03-15 (replication)"}
PKT_BYTES, SLICE_S = 60, 120


def boot_ratio(num: np.ndarray, den: np.ndarray, n=4000, seed=0) -> tuple[float, float, float]:
    rng = np.random.default_rng(seed)
    idx = rng.integers(0, len(num), (n, len(num)))
    r = num[idx].mean(axis=1) / np.maximum(den[idx].mean(axis=1), 1e-12)
    return float(num.mean() / max(den.mean(), 1e-12)), float(np.percentile(r, 2.5)), float(np.percentile(r, 97.5))


def main() -> None:
    idx, base_cache = {}, {}
    rows = []
    for path in sorted(glob.glob(str(OUT / "b_*.npz"))):
        m = PAT.match(Path(path).name)
        if not m:
            continue
        day, gate, mode, f, g = m.group(1), m.group(2), m.group(3), int(m.group(4)), int(m.group(5))
        if day not in idx:
            idx[day] = FlowIndex(flow_ids(np.load(OUT / f"stream_{day}.npy"), 1 << 62))
        bkey = (day, gate, "polyirr" if mode == "k0" else "crc", g)
        if bkey not in base_cache:
            name = (f"a_{day}_{gate}_polyirr_{g}_at{g}.npz" if mode == "k0" else f"a_{day}_{gate}_crc_at{g}.npz")
            base_cache[bkey] = downgraded_flows(np.load(OUT / name)["outcome"], idx[day])
        z = np.load(path)
        flag = downgraded_flows(z["benign_outcome"], idx[day])
        base = base_cache[bkey]
        code = idx[day].code
        n_a = int(z["n_attacker_packets"])
        rows.append({"day": day, "gate": gate, "mode": mode, "f": f, "g": g,
                     "excess_flows": int(flag.sum()) - int(base.sum()),
                     "excess_pkts": int(flag[code].sum()) - int(base[code].sum()),
                     "attacker_packets": n_a, "attacker_flows": len(z["atk_owned"]),
                     "held90": float(np.mean(z["atk_owned"] >= 0.9 * z["atk_packets"])),
                     "occupancy": float((z["atk_owned"] >= 0.9 * z["atk_packets"]).sum() / 65536),
                     "pps": n_a / SLICE_S, "mbps": n_a * PKT_BYTES * 8 / SLICE_S / 1e6})
    df = pd.DataFrame(rows)
    df.to_csv(OUT / "g2b_fill_summary.csv", index=False)
    L = ["# G2b fill arms on MAWI: excess benign downgrade against attacker cost", "",
         ("Generated by `scripts/g2b_report.py` from `results/g2/b_*.npz`. Analytical abstraction (see `dgrade.inject`): "
          "k1 gives the adversary distinct slots, b0l is the decision baseline (same benign hash as k1, adversary on "
          "uniform random slots), k0 keys the benign hash with an irreducible polynomial and the adversary lands on "
          "uniform random slots. Excess = benign flows downgraded in the attack run minus the paired no-attack run. "
          "Occupancy = attacker flows holding a slot for at least 90% of their packets, over 65,536."), ""]
    for day, dname in DAYS.items():
        for gate in ("oracle", "model"):
            d = df[(df.day == day) & (df.gate == gate)]
            if not len(d):
                continue
            L += [f"## {dname}, {gate} gate", "", ("| f | mode | draws | occupancy | attacker packets/s | Mb/s | excess benign flows | "
                  "excess per attacker packet ×10⁶ [95% CI] |"), "|---|---|---|---|---|---|---|---|"]
            for f in sorted(d.f.unique()):
                for mode in ("k1", "b0l", "k0"):
                    x = d[(d.f == f) & (d["mode"] == mode)]
                    if not len(x):
                        continue
                    r = boot_ratio(x.excess_flows.to_numpy(float), x.attacker_packets.to_numpy(float))
                    L.append(f"| {f}% | {mode} | {len(x)} | {x.occupancy.mean():.2%} | {x.pps.mean():,.0f} | {x.mbps.mean():.1f} | "
                             f"{x.excess_flows.mean():,.0f} | {r[0] * 1e6:.2f} [{r[1] * 1e6:.2f}, {r[2] * 1e6:.2f}] |")
            L.append("")
    (ROOT / "docs/results_g2b_fill.md").write_text("\n".join(L) + "\n")
    print("\n".join(L))


if __name__ == "__main__":
    main()
