"""H3 (stealth) from the fill arms -> docs/results_g2b_h3.md (docs/preregistration.md, G2b entry).

Excess = benign flows downgraded in the attack run minus the paired no-attack run (B0-L, oracle gate). rho* = the attacker's sustained
new-flow rate at the smallest fill fraction whose excess reaches 50% of the benign long flows, over R = 65,536 / 0.268 s.
Holders send 4 packets/s, 60-byte packets, and rotate before 2,048 packets (about 500 s), so the sustained new-flow rate is
f * 65,536 / 500 per second. Detector thresholds are quantiles of the benign 1-second bins (bins 5 and later; warm-up excluded)
of the PRIMARY day, frozen there and applied to both days; new flows per /24 is not evaluated (attacker source diversity is not modelled).
Alarm rates: each 1 s bin carries the benign count plus the attacker's count (4 packets per holder per second; new flows Poisson at the
steady-state rotation rate; the start-up transient of the first 5 s, when every holder starts, is shown separately) and is compared with the
frozen threshold. f is nominal holders per slot; holders draw slots with replacement, so the share of distinct slots targeted is 1 - exp(-f).
"""

from __future__ import annotations

import glob
import re
from pathlib import Path

import numpy as np

from dgrade.flowstats import FlowIndex, downgraded_flows

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "results/g2"
DAYS = {"p": "2022-09-14 (primary)", "r": "2023-03-15 (replication)"}
PAT = re.compile(r"b_([pr])_oracle_b0l_(\d+)_at(\d+)\.npz")
R = 65536 / 0.268435
ROT_S, HOLD_PPS, PKT_B, SLICE = 500.0, 4.0, 60, 120
QS = (50, 90, 99, 99.9)
RAMP_S = 5.0


def bins(day: str):
    pk = np.load(OUT / f"stream_{day}.npy")
    idx = FlowIndex(np.load(OUT / f"targeted_prep_{day}.npz")["code"])
    sec = (pk["ts_ns"] // 10**9).astype(np.int64)
    first = idx.order[idx.start]
    nf = np.bincount(sec[first], minlength=120)[5:120]
    pps = np.bincount(sec, minlength=120)[5:120]
    mbps = np.bincount(sec, weights=pk["total_len"].astype(float), minlength=120)[5:120] * 8 / 1e6
    return pk, idx, nf.astype(float), pps.astype(float), mbps


def main() -> None:
    data = {d: bins(d) for d in DAYS}
    thr = {q: (np.percentile(data["p"][2], q), np.percentile(data["p"][3], q), np.percentile(data["p"][4], q)) for q in QS}
    L = ["# G2b H3 (stealth): the cost of a fill attack against benign detector thresholds", "",
         ("Generated by `scripts/g2b_h3_report.py`. Fill with random-slot holders at 4 packets/s (60 bytes), oracle gate; excess = benign "
          "flows downgraded above the paired no-attack run; long flows = benign flows with more than 50 packets. Sustained new-flow rate "
          f"assumes holders rotate before 2,048 packets (about {ROT_S:.0f} s). Thresholds are benign quantiles of 1-second bins of the "
          "primary day, applied to both days. R = 65,536 / 0.268 s = "
          f"{R:,.0f} flows/s."), "",
          "Benign quantiles (primary day): " + "; ".join(
              f"p{q:g}: {t[0]:,.0f} new flows/s, {t[1]:,.0f} packets/s, {t[2]:,.0f} Mb/s" for q, t in thr.items()), ""]
    L += ["Benign-only alarm rate (fraction of 1-second bins above the frozen primary-day threshold; the primary day is about "
          "1% at p99 by construction, the replication day is out of sample):", "",
          "| day | new flows/s p99 | packets/s p99 | packets/s p99.9 | Mb/s p99 |", "|---|---|---|---|---|"]
    for day, dn in DAYS.items():
        _p, _i, nf_, pps_, mbps_ = data[day]
        L.append(f"| {dn} | {np.mean(nf_ > thr[99][0]):.1%} | {np.mean(pps_ > thr[99][1]):.1%} | "
                 f"{np.mean(pps_ > thr[99.9][1]):.1%} | {np.mean(mbps_ > thr[99][2]):.1%} |")
    L.append("")
    for day, dn in DAYS.items():
        _pk, idx, nf, pps, mbps = data[day]
        n_long = int((idx.n_pkts > 50).sum())
        by_f: dict[int, list[int]] = {}
        for path in sorted(glob.glob(str(OUT / "b_*.npz"))):
            m = PAT.match(Path(path).name)
            if not m or m.group(1) != day:
                continue
            f, g = int(m.group(2)), int(m.group(3))
            base = OUT / f"a_{day}_oracle_crc_at{g}.npz"
            if not base.exists():
                continue
            ex = (int(downgraded_flows(np.load(path)["benign_outcome"], idx).sum())
                  - int(downgraded_flows(np.load(base)["outcome"], idx).sum()))
            by_f.setdefault(f, []).append(ex)
        L += [f"## {dn}: {n_long:,} benign long flows", "",
              ("| f (nominal holders per slot) | draws | excess flows | share of long flows | distinct slots targeted | attacker packets/s | Mb/s | "
               "sustained new flows/s | ρ* if this f | benign+attack bins above p99 / p99.9 packets/s | above p99 new flows/s "
               "(steady state) | above p99 Mb/s | start-up bins (first 5 s) above p99 new flows/s |"),
              "|---|---|---|---|---|---|---|---|---|---|---|---|---|"]
        for f in sorted(by_f):
            e = np.array(by_f[f], float)
            hold = f / 100 * 65536
            a_pps, a_mbps, a_nf = hold * HOLD_PPS, hold * HOLD_PPS * PKT_B * 8 / 1e6, hold / ROT_S
            a_nf_bins = np.random.default_rng(7).poisson(a_nf, len(nf))           # steady-state new flows per 1 s bin
            rate = lambda v, t: float(np.mean(v > t))
            ramp_nf = hold / RAMP_S                                                # holders start uniformly over the ramp
            L.append(f"| {f}% | {len(e)} | {e.mean():,.0f} | {e.mean() / n_long:.1%} | {1 - np.exp(-f / 100):.0%} | {a_pps:,.0f} | {a_mbps:.0f} | {a_nf:.0f} | "
                     f"{a_nf / R:.1e} | {rate(pps + a_pps, thr[99][1]):.0%} / {rate(pps + a_pps, thr[99.9][1]):.0%} | "
                     f"{rate(nf + a_nf_bins, thr[99][0]):.0%} | {rate(mbps + a_mbps, thr[99][2]):.0%} | "
                     f"{'above' if ramp_nf > thr[99][0] else 'below'} ({ramp_nf:,.0f}/s vs {thr[99][0]:,.0f}/s) |")
        fs = sorted(by_f)
        share = [np.mean(by_f[f]) / n_long for f in fs]
        hit = next((i for i, s in enumerate(share) if s >= 0.5), None)
        if hit is None:
            L += ["", f"The 50% target is not reached within the fill fractions run (largest: {fs[-1]}% gives {share[-1]:.1%}).", ""]
        else:
            lo = hit - 1
            f50 = fs[hit] if lo < 0 else fs[lo] + (0.5 - share[lo]) * (fs[hit] - fs[lo]) / (share[hit] - share[lo])
            a_nf = f50 / 100 * 65536 / ROT_S
            L += ["", (f"Smallest fill reaching 50% of benign long flows (linear interpolation): f ≈ {f50:.0f}%; sustained new-flow rate "
                  f"≈ {a_nf:.0f}/s; ρ* ≈ {a_nf / R:.1e}."), ""]
    (ROOT / "docs/results_g2b_h3.md").write_text("\n".join(L) + "\n")
    print("\n".join(L))


if __name__ == "__main__":
    main()
