"""G4a diagnosis -> docs/results_g4a_diagnosis.md: why rent admission recovers so little (all numbers computed here).

(1) Rate distribution of benign oracle-long flows (the pre-registered report): how many benign flows a rate threshold would evict.
(2) Split of the fill attack's excess benign downgraded flows into flows refused at their first packet (newcomers) and flows that
    held a slot and lost it (displaced).
(3) Packet-weighted recovery next to the flow-weighted one used by the pre-registered M2.
Fill f = 10%, random-slot holders (b0l), oracle gate. Draw = clock start; percentile bootstrap over draws.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np

from dgrade.flowstats import FlowIndex, downgraded_flows

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "results/g2"
DAYS = {"p": "2022-09-14 (primary)", "r": "2023-03-15 (replication)"}
CONFIGS = ["d1", "d3c8", "d3c16", "d3c32", "d3a"]


def ci(x, n=4000, seed=0):
    rng = np.random.default_rng(seed)
    m = np.array([rng.choice(x, len(x)).mean() for _ in range(n)])
    return float(np.percentile(m, 2.5)), float(np.percentile(m, 97.5))


def main() -> None:
    L = ["# G4a diagnosis: why rent admission recovers so little", "",
         ("Generated by `scripts/g4_diagnose.py`. Oracle gate, fill f = 10% with random-slot holders sending 4 packets per "
          "second. *Refused* = an excess downgraded flow whose first packet was refused a slot by an active holder; *displaced* = "
          "one whose first packet took a slot and which later lost it."), "", "## 1. Rate of benign long flows", "",
         "| day | long flows (duration > 0.5 s) | share below 2 pkt/s | below 4 | below 8 | below 16 | below 32 | median rate |",
         "|---|---|---|---|---|---|---|---|"]
    idx = {}
    for d, name in DAYS.items():
        pk = np.load(OUT / f"stream_{d}.npy")
        idx[d] = FlowIndex(np.load(OUT / f"targeted_prep_{d}.npz")["code"])
        n, t = idx[d].n_pkts, pk["ts_ns"][idx[d].order]
        dur = (t[idx[d].start + n - 1] - t[idx[d].start]) / 1e9
        ok = (n > 50) & (dur > 0.5)
        rate = n[ok] / dur[ok]
        L.append(f"| {name} | {int(ok.sum()):,} | " + " | ".join(f"{np.mean(rate < r):.1%}" for r in (2, 4, 8, 16, 32))
                 + f" | {np.median(rate):.1f} pkt/s |")
    L += ["", ("A holder needs at least one packet per 268 ms, about 4 pkt/s. Any threshold that evicts it also evicts the share "
          "of benign long flows shown for 'below 4' and more."), "", "## 2. Where the excess goes", "",
          ("| day | config | draws | excess flows: refused / displaced | packets downgraded above no-attack (undefended = 100%) | "
          "packet-weighted recovery [CI] | flow-weighted recovery [CI] |"), "|---|---|---|---|---|---|---|"]
    for d, name in DAYS.items():
        ix = idx[d]
        first = ix.order[ix.start]
        n_draws = 30 if d == "p" else 10
        rows = {c: [] for c in ("undef", *CONFIGS)}
        for g in range(n_draws):
            base_o = OUT / f"a_{d}_oracle_crc_at{g}.npz"
            und_o = OUT / f"b_{d}_oracle_b0l_10_at{g}.npz"
            if not (base_o.exists() and und_o.exists()):
                continue
            base = downgraded_flows(np.load(base_o)["outcome"], ix)
            bp = base[ix.code].sum()
            for c in ("undef", *CONFIGS):
                p = und_o if c == "undef" else OUT / f"b_{d}_oracle_b0l_10_at{g}_p_{c}.npz"
                if not p.exists():
                    continue
                o = np.load(p)["benign_outcome"]
                fl = downgraded_flows(o, ix)
                ex = fl & ~base
                fo = o[first]
                rows[c].append((int(ex.sum()), int((ex & (fo == 3)).sum()), int((ex & np.isin(fo, (1, 2))).sum()),
                                int(fl[ix.code].sum() - bp)))
        u = np.array(rows["undef"])
        if not len(u):
            continue
        for c in ("undef", *CONFIGS):
            a = np.array(rows[c])
            if len(a) != len(u):
                continue
            pr = 1 - a[:, 3] / np.maximum(u[:, 3], 1)
            fr = 1 - a[:, 0] / np.maximum(u[:, 0], 1)
            plo, phi = ci(pr)
            flo, fhi = ci(fr)
            L.append(f"| {name} | {c if c != 'undef' else 'undefended'} | {len(a)} | {a[:, 1].mean():.0f} / {a[:, 2].mean():.0f} | "
                     f"{a[:, 3].mean() / u[:, 3].mean():.0%} | " + ("n/a | n/a |" if c == "undef" else
                     f"{pr.mean():.2f} [{plo:.2f}, {phi:.2f}] | {fr.mean():.2f} [{flo:.2f}, {fhi:.2f}] |"))
    L += ["", ("Recovery is measured, as pre-registered, against the *undefended* no-attack run. d1 also lowers the no-attack "
               "baseline (the wrap fix's benign gain), so d1's packet-weighted 'recovery' is mostly not attack mitigation; the "
               "gain specific to rent admission is a d3 row minus the d1 row. Age-only eviction (d3a) evicts holders and slow "
               "benign flows alike and makes the packet total worse than undefended. The packet-weighted recovery is exploratory: the "
               "pre-registered M2 is flow-weighted and fails on both days, and the packet-weighted figure is not consistent across the "
               "two days, so no claim rests on it."), ""]
    (ROOT / "docs/results_g4a_diagnosis.md").write_text("\n".join(L) + "\n")
    print("\n".join(L))


if __name__ == "__main__":
    main()
