"""G4 M1 on PeerRush: macro-F1 cost of each defence with no attack -> docs/results_g4_peerrush.md.

Cost = macro-F1(undefended run at the same clock) - macro-F1(defended run at the same clock), packet level, against the
capture labels; positive means the defence made accuracy worse. Pass (docs/preregistration.md, G4 entry, M1) if the upper
bound of the cost is at most 0.01. Draw = clock start (30 of them); percentile bootstrap over draws, 98.33% for the D3
family (Holm, three r_min values) and 95% otherwise. PeerRush and MAWI are never pooled.
"""

from __future__ import annotations

import itertools
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "results/g1"
N_CLASS = 3
CONFIGS = ["d1", "d3c8", "d3c16", "d3c32", "d3a"]
FAMILY = {"d3c8", "d3c16", "d3c32"}
LIMIT = 0.01


def class_of(result: np.ndarray) -> np.ndarray:
    r = result.astype(np.int64)
    return np.where(r == 0, -1, (r - 1) % 50)


def confusion(truth, pred, perm) -> np.ndarray:
    p = np.where(pred < 0, 3, np.asarray(perm)[np.clip(pred, 0, N_CLASS - 1)])
    return np.bincount(truth.astype(np.int64) * 4 + p, minlength=12).reshape(3, 4)


def macro_f1(cm) -> float:
    f = []
    for c in range(N_CLASS):
        tp, fp, fn = cm[c, c], cm[:, c].sum() - cm[c, c], cm[c].sum() - cm[c, c]
        f.append(0.0 if tp == 0 else 2 * tp / (2 * tp + fp + fn))
    return float(np.mean(f))


def boot(x: np.ndarray, level: float, n=4000, seed=0) -> tuple[float, float]:
    rng = np.random.default_rng(seed)
    m = np.array([rng.choice(x, len(x)).mean() for _ in range(n)])
    a = (1 - level) / 2 * 100
    return float(np.percentile(m, a)), float(np.percentile(m, 100 - a))


def main() -> None:
    z = np.load(OUT / "stream.npz")
    lab = z["lab"]
    iso0 = np.load(OUT / "g1b_iso_at0.npz")
    keep = iso0["outcome"] != 5
    truth = lab[keep]
    perms = list(itertools.permutations(range(N_CLASS)))
    sc = {p: macro_f1(confusion(truth, class_of(iso0["result"][keep]), p)) for p in perms}
    perm = max(sc, key=sc.get)

    def f1(name: str) -> float:
        r = np.load(OUT / name)
        return macro_f1(confusion(truth, class_of(r["result"][keep]), perm))

    L = ["# G4 M1 on PeerRush: macro-F1 cost of each defence, no attack", "",
         ("Generated by `scripts/g4_peerrush_report.py`. Cost = macro-F1 of the undefended run minus macro-F1 of the defended run at "
          f"the same clock start (positive = worse). Pass if the upper bound of the cost is at most {LIMIT}. Class mapping fixed from "
          f"the isolated run (F1 {sc[perm]:.3f}). Draws are the 30 clock starts."), "",
          "| config | draws | undefended macro-F1 | defended macro-F1 | cost [CI] | M1 |", "|---|---|---|---|---|---|"]
    for cfg in CONFIGS:
        rows = []
        for g in range(30):
            base, dfn = f"g1b_crc_at{g}.npz", f"g1b_crc_at{g}_p_{cfg}.npz"
            if (OUT / base).exists() and (OUT / dfn).exists():
                rows.append((f1(base), f1(dfn)))
        if not rows:
            continue
        a = np.array(rows)
        cost = a[:, 0] - a[:, 1]
        lo, hi = boot(cost, 0.9833 if cfg in FAMILY else 0.95)
        L.append(f"| {cfg} | {len(a)} | {a[:, 0].mean():.4f} | {a[:, 1].mean():.4f} | {cost.mean():+.4f} [{lo:+.4f}, {hi:+.4f}] | "
                 f"{'pass' if hi <= LIMIT else 'fail'} |")
    (ROOT / "docs/results_g4_peerrush.md").write_text("\n".join(L) + "\n")
    print("\n".join(L))


if __name__ == "__main__":
    main()
