"""G4a report: defences against benign cost and fill attacks on MAWI -> docs/results_g4a.md.

Follows docs/preregistration.md (G4 entry). Oracle gate. Per configuration and day:
M1 benign cost with no attack (downgraded-packet share change against the paired undefended no-attack run);
M2 recovery = 1 - (defended attack - undefended no-attack) / (undefended attack - undefended no-attack), on excess benign
downgraded flows, at equal attacker packets (same draw, same holders); M3 attacker packets per held slot-second and the
equal-budget cost multiple. Draw is the bootstrap unit; the D3 family uses 98.33% intervals (Holm/Bonferroni, 3 r_min).
"""

from __future__ import annotations

import glob
import re
from pathlib import Path

import numpy as np
import pandas as pd

from dgrade.flowstats import FlowIndex, downgraded_flows

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "results/g2"
DAYS = {"p": "2022-09-14 (primary)", "r": "2023-03-15 (replication)"}
HOLD_S = 0.25                                   # a held packet covers one 250 ms holder interval
CONFIGS = ["d1", "d3c8", "d3c16", "d3c32", "d3a"]
RMIN = {"d3c8": 8, "d3c16": 16, "d3c32": 32}
M1_PP, M1_DELTA = 0.005, 0.01
PAT_A = re.compile(r"a_([pr])_oracle_crc_at(\d+)_p_(d\w+)\.npz")
PAT_B = re.compile(r"b_([pr])_oracle_b0l_(\d+)_at(\d+)_p_(d\w+)\.npz")


def boot(x: np.ndarray, q, n=4000, seed=0):
    rng = np.random.default_rng(seed)
    m = np.array([rng.choice(x, len(x)).mean() for _ in range(n)])
    return np.percentile(m, q)


def recovery_ci(num: np.ndarray, den: np.ndarray, level: float, n=4000, seed=0):
    rng = np.random.default_rng(seed)
    i = rng.integers(0, len(num), (n, len(num)))
    r = 1 - num[i].mean(axis=1) / np.maximum(den[i].mean(axis=1), 1e-9)
    a = (1 - level) / 2 * 100
    return 1 - num.mean() / max(den.mean(), 1e-9), float(np.percentile(r, a)), float(np.percentile(r, 100 - a))


def main() -> None:
    idx = {d: FlowIndex(np.load(OUT / f"targeted_prep_{d}.npz")["code"]) for d in DAYS}
    cache: dict[str, np.ndarray] = {}

    def outcome(name: str, key: str = "outcome") -> np.ndarray:
        if name not in cache:
            cache[name] = np.load(OUT / name)[key]
        return cache[name]

    def flows_down(day: str, name: str, key: str = "outcome") -> int:
        return int(downgraded_flows(outcome(name, key), idx[day]).sum())

    def pkt_share(day: str, name: str) -> float:
        return float(downgraded_flows(outcome(name), idx[day])[idx[day].code].mean())

    m1, m2 = [], []
    for path in sorted(glob.glob(str(OUT / "a_*_p_d*.npz"))):
        m = PAT_A.match(Path(path).name)
        if m:
            day, g, cfg = m.group(1), int(m.group(2)), m.group(3)
            base = f"a_{day}_oracle_crc_at{g}.npz"
            oc, ob = outcome(Path(path).name), outcome(base)
            m1.append({"day": day, "cfg": cfg, "g": g,
                       "dshare": pkt_share(day, Path(path).name) - pkt_share(day, base),
                       "dcoll": float(np.mean(oc == 3) - np.mean(ob == 3)), "dempty": float(np.mean(oc == 6) - np.mean(ob == 6))})
    for path in sorted(glob.glob(str(OUT / "b_*_p_d*.npz"))):
        m = PAT_B.match(Path(path).name)
        if not m:
            continue
        day, f, g, cfg = m.group(1), int(m.group(2)), int(m.group(3)), m.group(4)
        undef = f"b_{day}_oracle_b0l_{f}_at{g}.npz"
        base = f"a_{day}_oracle_crc_at{g}.npz"
        if not (OUT / undef).exists():
            continue
        z = np.load(path)
        base_n = flows_down(day, base)
        d_def = flows_down(day, Path(path).name, "benign_outcome") - base_n
        d_und = flows_down(day, undef, "benign_outcome") - base_n
        owned = float(np.sum(z["atk_owned"]))
        m2.append({"day": day, "f": f, "cfg": cfg, "g": g, "excess_def": d_def, "excess_undef": d_und,
                   "n_a": int(z["n_attacker_packets"]), "cost_per_slot_s": z["n_attacker_packets"] / max(owned * HOLD_S, 1e-9)})
    a1, a2 = pd.DataFrame(m1), pd.DataFrame(m2)
    a1.to_csv(OUT / "g4a_m1.csv", index=False)
    a2.to_csv(OUT / "g4a_m2.csv", index=False)

    L = ["# G4a results: defences on MAWI (oracle gate, emulator)", "",
         ("Generated by `scripts/g4_report.py` from `results/g2/`. Defences (see `dgrade.defences`): d1 = wrap fix (clock, takeover "
          "refresh, packet-gap timestamp); d3cR = d1 plus credit-based rent admission at R packets per second; d3a = d1 plus "
          "age-only eviction after 1 s. Attack: fill with random-slot holders (b0l) at 4 packets per second per holder, "
          "paired by draw with the undefended runs. D2 (secret polynomial) is judged from the k0 fill runs (see the fill report). "
          "Intervals: 95% percentile bootstrap over draws; the D3 family uses 98.33% (Holm, three r_min values)."), ""]
    L += ["## M1: benign cost with no attack", "",
          f"Pass if the upper bound of the downgraded-packet-share change is at most {M1_PP * 100:.1f} percentage points.", "",
          "| day | config | draws | Δ downgraded packets, pp [CI] | Δ collision packets, pp | Δ empty-slot refusals, pp | M1 |",
          "|---|---|---|---|---|---|---|"]
    m1pass = {}
    for day, dn in DAYS.items():
        for cfg in CONFIGS:
            d = a1[(a1.day == day) & (a1.cfg == cfg)] if len(a1) else a1
            if not len(d):
                continue
            q = (1.67, 98.33) if cfg in RMIN else (2.5, 97.5)
            lo, hi = boot(d.dshare.to_numpy(), q)
            ok = hi <= M1_PP
            m1pass[(day, cfg)] = ok
            L.append(f"| {dn} | {cfg} | {len(d)} | {d.dshare.mean() * 100:+.3f} [{lo * 100:+.3f}, {hi * 100:+.3f}] | "
                     f"{d.dcoll.mean() * 100:+.3f} | {d.dempty.mean() * 100:+.3f} | {'pass' if ok else 'fail'} |")
    L += ["", "## M2 and M3: fill attack at equal attacker packets", "",
          ("Excess = benign flows downgraded minus the undefended no-attack run of the same draw. Recovery = 1 - defended excess / "
           "undefended excess. Cost per held slot-second = attacker packets / (holder packets that kept a slot × 0.25 s); "
           "the undefended value is about 4."), "",
          ("| day | f | config | draws | undefended excess | defended excess | recovery [CI] | M2 (≥ 0.5) | attacker packets per held slot-second | "
          "equal-budget cost multiple | M3 |"), "|---|---|---|---|---|---|---|---|---|---|---|"]
    for day, dn in DAYS.items():
        for f in (10, 25):
            for cfg in CONFIGS:
                d = a2[(a2.day == day) & (a2.f == f) & (a2.cfg == cfg)] if len(a2) else a2
                if not len(d):
                    continue
                level = 0.9833 if cfg in RMIN else 0.95
                r, lo, hi = recovery_ci(d.excess_def.to_numpy(float), d.excess_undef.to_numpy(float), level)
                ok2 = lo >= 0.5
                mult = d.excess_undef.mean() / max(d.excess_def.mean(), 1e-9)
                cost = d.cost_per_slot_s.mean()
                rm = RMIN.get(cfg)
                ok3 = (cost >= 0.9 * rm and mult >= 0.5 * rm / 4) if rm else None
                L.append(f"| {dn} | {f}% | {cfg} | {len(d)} | {d.excess_undef.mean():,.0f} | {d.excess_def.mean():,.0f} | "
                         f"{r:.2f} [{lo:.2f}, {hi:.2f}] | {'pass' if ok2 else 'fail'} | {cost:.2f} | {mult:.2f} | "
                         f"{'n/a' if ok3 is None else ('pass' if ok3 else 'fail')} |")
    L += ["", "## D2: secret irreducible polynomial under the fill attack", "",
          ("Prediction (pre-registered): D2 leaves the fill excess within ±10% of undefended. Each side is measured against its own "
           "no-attack baseline (undefended: unkeyed hash; D2: keyed hash at the same clock, same draw). The ratio is keyed excess over unkeyed "
           "excess, mean of draws with a bootstrap over draws."), "",
          "| day | f | draws | unkeyed excess (flows) | keyed excess (flows) | ratio [95% CI] | within ±10% |", "|---|---|---|---|---|---|---|"]
    for day, dn in DAYS.items():
        for f in (10, 25):
            eu, ek = [], []
            for g in range(30 if (day == "p" and f == 10) else 10):
                fu, fk = f"b_{day}_oracle_b0l_{f}_at{g}.npz", f"b_{day}_oracle_k0_{f}_at{g}.npz"
                bu, bk = f"a_{day}_oracle_crc_at{g}.npz", f"a_{day}_oracle_polyirr_{g}_at{g}.npz"
                if all((OUT / x).exists() for x in (fu, fk, bu, bk)):
                    eu.append(flows_down(day, fu, "benign_outcome") - flows_down(day, bu))
                    ek.append(flows_down(day, fk, "benign_outcome") - flows_down(day, bk))
            if not eu:
                continue
            eu, ek = np.array(eu, float), np.array(ek, float)
            rng = np.random.default_rng(0)
            i = rng.integers(0, len(eu), (4000, len(eu)))
            r = ek[i].mean(axis=1) / np.maximum(eu[i].mean(axis=1), 1e-9)
            lo, hi = np.percentile(r, [2.5, 97.5])
            L.append(f"| {dn} | {f}% | {len(eu)} | {eu.mean():,.0f} | {ek.mean():,.0f} | {ek.mean() / eu.mean():.2f} [{lo:.2f}, {hi:.2f}] | "
                     f"{'yes' if lo >= 0.9 and hi <= 1.1 else 'no'} |")
    (ROOT / "docs/results_g4a.md").write_text("\n".join(L) + "\n")
    print("\n".join(L))


if __name__ == "__main__":
    main()
