"""D1 split into its three changes on MAWI (post-hoc diagnostic) -> docs/results_g4a_d1parts.md.

Oracle gate, B0-L fill at 10%, excess in benign flows downgraded (downgraded_flows on the benign packets).
Two recoveries, so a defence's own benign gain is not counted as mitigation:
  G4a-style   1 - (defended attack - UNDEFENDED no-attack) / (undefended attack - undefended no-attack)   [what results_g4a.md reports]
  self-baseline (mitigation)   1 - (defended attack - DEFENDED no-attack) / (undefended attack - undefended no-attack)
Benign gain = undefended no-attack - defended no-attack, in downgraded flows. Percentile bootstrap over draws (clock starts).
"""

from __future__ import annotations

import re
from pathlib import Path

import numpy as np

from dgrade.flowstats import FlowIndex, downgraded_flows

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "results/g2"
DAYS = {"p": "2022-09-14 (primary)", "r": "2023-03-15 (replication)"}
ARMS = [("d1w", "no wrap window only"), ("d1t", "takeover refresh only"), ("d1i", "packet-gap timestamp only"), ("d1", "all three")]
F = 10


def ci(v: np.ndarray, n: int = 4000, seed: int = 0) -> tuple[float, float]:
    rng = np.random.default_rng(seed)
    m = np.array([rng.choice(v, len(v)).mean() for _ in range(n)])
    return float(np.percentile(m, 2.5)), float(np.percentile(m, 97.5))


def ratio_ci(num: np.ndarray, den: np.ndarray, n: int = 4000, seed: int = 0) -> tuple[float, float, float]:
    rng = np.random.default_rng(seed)
    i = rng.integers(0, len(num), (n, len(num)))
    r = 1 - num[i].mean(1) / np.maximum(den[i].mean(1), 1e-9)
    return 1 - num.mean() / max(den.mean(), 1e-9), float(np.percentile(r, 2.5)), float(np.percentile(r, 97.5))


def main() -> None:
    L = ["# D1 split into its three changes on MAWI (post-hoc diagnostic)", "",
         ("Generated by `scripts/g4a_d1parts_report.py` from `results/g2/`. Oracle gate, random-slot fill at 10% of 65,536 slots (nominal holder "
          "load), excess = benign flows downgraded. Two recoveries are shown. **G4a-style** measures the defended attack against the "
          "*undefended* no-attack run, as `results_g4a.md` does, so a defence's own benign gain counts as mitigation. **Mitigation** measures "
          "it against the defence's *own* no-attack run. Benign gain = undefended no-attack minus defended no-attack, in downgraded flows. "
          "Intervals: 95% percentile bootstrap over draws (clock starts)."), ""]
    for day, dn in DAYS.items():
        idx = FlowIndex(np.load(OUT / f"targeted_prep_{day}.npz")["code"])
        cache: dict[tuple[str, str], int] = {}

        def flows(name: str, key: str) -> int:
            if (name, key) not in cache:
                cache[(name, key)] = int(downgraded_flows(np.load(OUT / name)[key], idx).sum())
            return cache[(name, key)]

        clocks = sorted(int(m.group(1)) for p in OUT.glob(f"b_{day}_oracle_b0l_{F}_at*.npz")
                        if (m := re.search(r"_at(\d+)\.npz$", p.name)))          # undefended runs only (no "_p_<defence>" suffix)
        rows = {}
        for arm, _ in ARMS:
            gs = [g for g in clocks if (OUT / f"b_{day}_oracle_b0l_{F}_at{g}_p_{arm}.npz").exists()
                  and (OUT / f"a_{day}_oracle_crc_at{g}_p_{arm}.npz").exists() and (OUT / f"a_{day}_oracle_crc_at{g}.npz").exists()]
            if not gs:
                continue
            base = np.array([flows(f"a_{day}_oracle_crc_at{g}.npz", "outcome") for g in gs], float)
            und = np.array([flows(f"b_{day}_oracle_b0l_{F}_at{g}.npz", "benign_outcome") for g in gs], float)
            dbase = np.array([flows(f"a_{day}_oracle_crc_at{g}_p_{arm}.npz", "outcome") for g in gs], float)
            dat = np.array([flows(f"b_{day}_oracle_b0l_{F}_at{g}_p_{arm}.npz", "benign_outcome") for g in gs], float)
            rows[arm] = (len(gs), und - base, dat - base, dat - dbase, base - dbase)
        if not rows:
            continue
        n_long = int((idx.n_pkts > 50).sum())
        L += [f"## {dn}: {n_long:,} benign long flows", "",
              "| arm | change | draws | undefended excess (flows) | defended excess vs undefended no-attack | defended excess vs own no-attack | "
              "benign gain (flows) | G4a-style recovery [CI] | mitigation [CI] |", "|---|---|---|---|---|---|---|---|---|"]
        for arm, what in ARMS:
            if arm not in rows:
                continue
            n, ex_u, ex_g, ex_s, gain = rows[arm]
            gr, glo, ghi = ratio_ci(ex_g, ex_u)
            mr, mlo, mhi = ratio_ci(ex_s, ex_u)
            L.append(f"| {arm} | {what} | {n} | {ex_u.mean():,.0f} | {ex_g.mean():,.0f} | {ex_s.mean():,.0f} | {gain.mean():+,.0f} "
                     f"[{ci(gain)[0]:+,.0f}, {ci(gain)[1]:+,.0f}] | {gr:+.2f} [{glo:+.2f}, {ghi:+.2f}] | {mr:+.2f} [{mlo:+.2f}, {mhi:+.2f}] |")
        L.append("")
    L += ["Reading: a mitigation below zero means the defence makes the fill attack's excess larger than it is against the shipped design. "
          "This is an emulator result; switch equivalence is unverified."]
    (ROOT / "docs/results_g4a_d1parts.md").write_text("\n".join(L) + "\n")
    print("\n".join(L))


if __name__ == "__main__":
    main()
