"""G5-0 gate (docs/preregistration.md, G5 entry): does phase-verdict agreement identify slots that are not needed? -> docs/results_g5_gate.md

Isolated PeerRush run (every flow has a slot), no attack. A *phase event* is a packet at which a flow's stored verdict changes to a phase
model's verdict (the switch then also has the per-packet fallback verdict for that packet). A flow is *agree-so-far* after a phase if its
full-model phase verdict equalled the fallback's at every phase reached and at least two phases were reached. Slot-seconds are approximated
by a flow's first-to-last-packet time from its second phase event, plus the 268 ms hold. Kill rule: the cost's upper 95% bound above 0.01, or
a slot-second share below 20%. The interval over clock starts is the pre-registered addition when the point estimate is within 0.005 of the limit.
"""

from __future__ import annotations

import itertools
from pathlib import Path

import numpy as np

from dgrade.flowstats import FlowIndex
from dgrade.netbeacon import PHASES, load_tables
from dgrade.netbeacon_sim import NetBeaconSim, TableModels, flow_ids

ROOT = Path(__file__).resolve().parents[1]
HOLD_NS = 268_000_000
LIMIT, SHARE_FLOOR = 0.01, 0.20


def cls(r: np.ndarray) -> np.ndarray:
    r = np.asarray(r).astype(np.int64)
    return np.where(r == 0, -1, (r - 1) % 50)


def macro_f1(truth, pred, perm) -> float:
    p = np.where(pred < 0, 3, np.asarray(perm)[np.clip(pred, 0, 2)])
    cm = np.bincount(truth.astype(int) * 4 + p, minlength=12).reshape(3, 4)
    f = []
    for c in range(3):
        tp = cm[c, c]
        fp, fn = cm[:, c].sum() - tp, cm[c].sum() - tp
        f.append(0 if tp == 0 else 2 * tp / (2 * tp + fp + fn))
    return float(np.mean(f))


def gate(grid: int) -> tuple[list[str], float, dict[int, float]]:
    z = np.load(ROOT / "results/g1/stream.npz")
    pk, lab = z["pk"], z["lab"]
    models = TableModels(load_tables(ROOT / "third_party/NetBeacon"))
    fid = flow_ids(pk, 1 << 62)
    idx = FlowIndex(fid)
    out = NetBeaconSim(models=models, clock_offset_ns=grid * ((1 << 32) // 30)).run(pk, isolate=fid)
    full, fb = cls(out["result"]), cls(models.pkt_codes(pk))
    src = out["source"]
    perm = max(itertools.permutations(range(3)), key=lambda p: macro_f1(lab, full, p))
    base = macro_f1(lab, full, perm)

    o, code = idx.order, idx.code
    s_sorted = src[o]
    same_flow = np.concatenate([[False], code[o][1:] == code[o][:-1]])
    prev = np.concatenate([[""], s_sorted[:-1]])
    is_phase = np.array([s.startswith("phase-") for s in s_sorted])
    ev_pos = np.flatnonzero(is_phase & ((~same_flow) | (s_sorted != prev)))
    ev_pkt = o[ev_pos]
    ev_flow = code[ev_pkt]
    ev_phase = np.array([int(s.split("-")[1]) for s in s_sorted[ev_pos]])
    ev_agree = full[ev_pkt] == fb[ev_pkt]

    L = ["# G5-0 gate: phase-verdict agreement on PeerRush (isolated, no attack)", "",
         ("Generated by `scripts/g5_gate.py`. Isolated reference run at clock grid 0 (the interval section uses six clock starts). "
          "Agreement compares the full model's phase verdict with the per-packet fallback verdict at the phase packet. "
          f"Reference macro-F1 {base:.4f}."), "",
         "## Agreement by phase", "", "| phase | events | agree | share |", "|---|---|---|---|"]
    for ph in PHASES:
        m = ev_phase == ph
        if m.any():
            L.append(f"| {ph} | {int(m.sum()):,} | {int(ev_agree[m].sum()):,} | {ev_agree[m].mean():.1%} |")

    seqs: dict[int, list[tuple[int, int, bool]]] = {}
    for f, ph, ag, pkt_i in zip(ev_flow, ev_phase, ev_agree, ev_pkt, strict=True):
        seqs.setdefault(int(f), []).append((int(ph), int(pkt_i), bool(ag)))
    L += ["", "## Persistence", "", "| after phase | flows agreeing at all phases so far | of those, agree at the next phase |", "|---|---|---|"]
    order = list(PHASES)
    for k in range(1, len(order) - 1):
        so_far = [s for s in seqs.values() if len(s) > k and all(a for _, _, a in s[:k])]
        if so_far:
            L.append(f"| {order[k - 1]} (k = {k}) | {len(so_far):,} | {np.mean([s[k][2] for s in so_far]):.1%} |")

    ts = pk["ts_ns"]
    total = agree_s = 0.0
    for f, s in seqs.items():
        t_first = ts[idx.order[idx.start[f]]]
        t_last = ts[idx.order[idx.start[f] + idx.n_pkts[f] - 1]]
        total += (t_last - t_first + HOLD_NS) / 1e9
        for k, (_, pkt_i, _ag) in enumerate(s):
            if not all(a for _, _, a in s[:k + 1]):
                break
            if k + 1 >= 2:
                t_next = ts[s[k + 1][1]] if k + 1 < len(s) else t_last
                agree_s += (t_next - ts[pkt_i]) / 1e9
    share = agree_s / total if total else 0.0
    L += ["", "## Slot-seconds", "",
          f"Share of slot-seconds (over flows that reach a phase event) spent in the agree-so-far state (at least two phases, all agreeing): **{share:.1%}**."]

    L += ["", "## Cost of forcing agree-so-far flows onto the fallback", "",
          "| force after phase | flows affected | packets affected | macro-F1 | change | vs limit 0.01 |", "|---|---|---|---|---|---|"]
    costs: dict[int, float] = {}
    for ph in (4, 8):
        mixed = full.copy()
        n_fl = 0
        for f, s in seqs.items():
            phases = [p for p, _, _ in s]
            if ph not in phases:
                continue
            k = phases.index(ph)
            if k + 1 >= 2 and all(a for _, _, a in s[:k + 1]):
                fl_pk = idx.order[idx.start[f]:idx.start[f] + idx.n_pkts[f]]
                after = fl_pk[ts[fl_pk] > ts[s[k][1]]]
                mixed[after] = fb[after]
                n_fl += 1
        f1 = macro_f1(lab, mixed, perm)
        costs[ph] = base - f1
        L.append(f"| {ph} | {n_fl:,} | {int(np.sum(mixed != full)):,} | {f1:.4f} | {f1 - base:+.4f} | "
                 f"{'over limit' if costs[ph] > LIMIT else 'within'} |")
    return L, share, costs


def main() -> None:
    L, share, costs = gate(0)
    rows = [(0, share, costs)] + [(g, *gate(g)[1:]) for g in (5, 10, 15, 20, 25)]
    c4, c8 = np.array([r[2][4] for r in rows]), np.array([r[2][8] for r in rows])
    rng = np.random.default_rng(0)
    hi4 = np.percentile([rng.choice(c4, len(c4)).mean() for _ in range(4000)], 97.5)
    hi8 = np.percentile([rng.choice(c8, len(c8)).mean() for _ in range(4000)], 97.5)
    L += ["", "## Interval over clock starts", "", "| clock grid | slot-second share | cost after phase 4 | cost after phase 8 |", "|---|---|---|---|"]
    L += [f"| {g} | {sh:.1%} | {cs[4]:+.4f} | {cs[8]:+.4f} |" for g, sh, cs in rows]
    kill = min(r[1] for r in rows) < SHARE_FLOOR or hi4 > LIMIT or hi8 > LIMIT
    L += ["", (f"Mean cost after phase 4: {c4.mean():.4f} (upper 95% bound {hi4:.4f}); after phase 8: {c8.mean():.4f} (upper 95% bound {hi8:.4f}); "
          f"limit {LIMIT}. Slot-second share floor {SHARE_FLOOR:.0%}."), "",
          f"**Gate: {'KILL V2-evict and V2-credit (pre-registered rule)' if kill else 'passes the pre-registered kill rule'}.**"]
    (ROOT / "docs/results_g5_gate.md").write_text("\n".join(L) + "\n")
    print("\n".join(L))


if __name__ == "__main__":
    main()
