"""G5 PeerRush labelled fill attack -> docs/results_g5_peerrush.md (docs/preregistration.md, G5 amendment).

Loss(run) = macro-F1(isolated full-model reference at the same clock start) - macro-F1(contended benign packets), against the capture
labels, on the 8,192-slot table. Excess(f) = Loss(undefended, fill f) - Loss(undefended, no attack) at the same clock start.
Recovery of a defence = (Loss_und(f) - Loss_def(f)) / Excess_und(f), the pre-registered quantity, measured against the undefended
no-attack run. Its parts are reported separately so a defence's own benign gain is not counted as mitigation:
    benign gain = Loss_und(0) - Loss_def(0);  mitigation = Excess_und(f) - (Loss_def(f) - Loss_def(0)).
Two intervals: percentile bootstrap over draws (clock starts, the pre-registered unit) and a bootstrap over benign flows
(all draws share one capture). Class mapping fixed on the isolated run at clock 0.
"""

from __future__ import annotations

import itertools
from pathlib import Path

import numpy as np

from dgrade.netbeacon_sim import tuple_table
from g4_peerrush_report import N_CLASS, class_of, confusion, macro_f1

ROOT = Path(__file__).resolve().parents[1]
G1, G5 = ROOT / "results/g1", ROOT / "results/g5"
FILL_CLOCKS = {10: list(range(0, 30, 3)), 25: [0, 6, 12, 18, 24]}
ARMS = ["d1", "d3c8", "d3c16"]
FAMILY = {"d3c8", "d3c16"}
N_BOOT, N_FLOW_BOOT = 4000, 200


def percentile_ci(x: np.ndarray, level: float) -> tuple[float, float]:
    a = (1 - level) / 2 * 100
    return float(np.percentile(x, a)), float(np.percentile(x, 100 - a))


def boot_draws(fn, n_draws: int, level: float, seed: int = 0) -> tuple[float, float]:
    """Percentile bootstrap over draws of ``fn(indices)``."""
    rng = np.random.default_rng(seed)
    v = np.array([fn(rng.integers(0, n_draws, n_draws)) for _ in range(N_BOOT)])
    return percentile_ci(v[np.isfinite(v)], level)


def main() -> None:
    z = np.load(G1 / "stream.npz")
    pk, lab = z["pk"], z["lab"]
    _, inv = tuple_table(pk["src_ip"], pk["dst_ip"], pk["src_port"], pk["dst_port"], pk["proto"])
    iso0 = np.load(G1 / "g1b_iso_at0.npz")
    keep = iso0["outcome"] != 5
    truth, flow = lab[keep].astype(np.int64), inv[keep]
    nf = int(flow.max()) + 1
    perms = list(itertools.permutations(range(N_CLASS)))
    perm = max(perms, key=lambda p: macro_f1(confusion(truth, class_of(iso0["result"][keep]), p)))

    def per_flow_cm(result: np.ndarray) -> np.ndarray:
        pred = class_of(result[keep])
        p = np.where(pred < 0, 3, np.asarray(perm)[np.clip(pred, 0, N_CLASS - 1)])
        return np.bincount(flow * 12 + truth * 4 + p, minlength=nf * 12).reshape(nf, 12).astype(np.float32)

    cache: dict[str, np.ndarray] = {}

    def cm(name: str, iso: bool = False) -> np.ndarray | None:
        path = (G1 if iso else G5) / name
        if not path.exists():
            return None
        if name not in cache:
            cache[name] = per_flow_cm(np.load(path)["result"])
        return cache[name]

    wcache: dict[str, np.ndarray] = {}

    def f1_of(name: str, iso: bool, k: int | None) -> float:
        """Macro-F1 of a run; k selects a benign-flow bootstrap replicate (None = the observed capture)."""
        if k is None:
            return macro_f1(cm(name, iso).sum(0).reshape(3, 4))
        if name not in wcache:
            wcache[name] = Wmat @ cm(name, iso)
        return macro_f1(wcache[name][k].reshape(3, 4))

    def key(f: int, arm: str, g: int) -> str:
        return f"pr_{f}_{arm}_at{g}.npz"

    def have(f: int, arm: str, clocks) -> list[int]:
        return [g for g in clocks if cm(key(f, arm, g)) is not None and cm(f"g1b_iso_at{g}.npz", True) is not None]

    memo: dict[tuple, float] = {}

    memo: dict[tuple, float] = {}

    def loss(f: int, arm: str, g: int, w=None) -> float:
        if (f, arm, g, w) not in memo:
            memo[(f, arm, g, w)] = f1_of(f"g1b_iso_at{g}.npz", True, w) - f1_of(key(f, arm, g), False, w)
        return memo[(f, arm, g, w)]

    rng = np.random.default_rng(1)
    Wmat = np.stack([np.bincount(rng.integers(0, nf, nf), minlength=nf) for _ in range(N_FLOW_BOOT)]).astype(np.float32)
    weights = range(N_FLOW_BOOT)

    def summarise(stat, n_draws: int, level: float) -> str:
        """stat(draw_idx, weights) -> float; point, draw CI, flow-cluster CI."""
        idx = np.arange(n_draws)
        point = stat(idx, None)
        lo, hi = boot_draws(lambda i: stat(i, None), n_draws, level)
        fl = np.array([stat(idx, w) for w in weights])
        flo, fhi = percentile_ci(fl[np.isfinite(fl)], level)
        return f"{point:+.4f} [{lo:+.4f}, {hi:+.4f}] / [{flo:+.4f}, {fhi:+.4f}]"

    L = ["# G5 on PeerRush: labelled fill attack and defences, 8,192-slot table", "",
         ("Generated by `scripts/g5_peerrush_report.py` from `results/g5/` and the isolated references in `results/g1/`. Loss = macro-F1 of "
          "the isolated reference at the same clock start minus macro-F1 of the contended benign packets. Each cell reads: point "
          "[95% percentile interval over draws (clock starts)] / [same over benign flows]. The D3 family uses 98.33% (Holm, two r_min values). "
          "f is the nominal holder load per slot; holders draw slots with replacement, so the distinct-slot share is 1 - exp(-f)."), ""]

    c_all = have(0, "und", range(30))
    L += ["## No attack: benign loss of the load-matched table (M1 baseline)", "",
          "| arm | draws | loss vs isolated | benign gain vs undefended (loss_und - loss_def) |", "|---|---|---|---|"]
    if c_all:
        L.append(f"| undefended | {len(c_all)} | {summarise(lambda i, w: np.mean([loss(0, 'und', c_all[j], w) for j in i]), len(c_all), 0.95)} | - |")
    for arm in ARMS:
        cs = [g for g in have(0, arm, FILL_CLOCKS[10]) if key(0, "und", g)]
        cs = [g for g in cs if cm(key(0, "und", g)) is not None]
        if cs:
            lv = 0.9833 if arm in FAMILY else 0.95
            L.append(f"| {arm} | {len(cs)} | {summarise(lambda i, w: np.mean([loss(0, arm, cs[j], w) for j in i]), len(cs), lv)} | "
                     f"{summarise(lambda i, w: np.mean([loss(0, 'und', cs[j], w) - loss(0, arm, cs[j], w) for j in i]), len(cs), lv)} |")

    for f in (10, 25):
        cs_und = [g for g in have(f, "und", range(30)) if cm(key(0, "und", g)) is not None]
        L += ["", f"## Fill f = {f}% (nominal; distinct slots targeted about {1 - np.exp(-f / 100):.0%})", ""]
        if not cs_und:
            L.append("No runs finished.")
            continue
        ex = lambda i, w, cs=cs_und: np.mean([loss(f, "und", cs[j], w) - loss(0, "und", cs[j], w) for j in i])
        s = summarise(ex, len(cs_und), 0.95)
        fl_ex = np.array([ex(np.arange(len(cs_und)), w) for w in weights])
        lower = min(boot_draws(lambda i: ex(i, None), len(cs_und), 0.95)[0], percentile_ci(fl_ex, 0.95)[0])
        if len(cs_und) < 5:
            lower = 0.0
        L += [f"Undefended excess loss over the no-attack run ({len(cs_und)} paired draws): {s}. "
              + ("Both intervals exclude zero (with at least 5 draws), so the attack's accuracy harm is resolved." if lower > 0 else
                 "**Fewer than 5 draws, or an interval (over draws or over flows) includes zero: the harm is not resolved at this fill and the recovery ratios below are not evaluated.**"), ""]
        L += ["| arm | draws | loss (defended) | benign gain | mitigation | recovery (pre-registered) | M2 (lower bound >= 0.5) |",
              "|---|---|---|---|---|---|---|"]
        for arm in ARMS:
            cs = [g for g in FILL_CLOCKS[f] if g in have(f, arm, FILL_CLOCKS[f]) and g in cs_und and cm(key(0, arm, g)) is not None
                  and cm(key(0, "und", g)) is not None]
            if not cs:
                continue
            lv = 0.9833 if arm in FAMILY else 0.95
            ld = lambda i, w: np.mean([loss(f, arm, cs[j], w) for j in i])
            gain = lambda i, w: np.mean([loss(0, "und", cs[j], w) - loss(0, arm, cs[j], w) for j in i])
            mit = lambda i, w: np.mean([(loss(f, "und", cs[j], w) - loss(0, "und", cs[j], w))
                                        - (loss(f, arm, cs[j], w) - loss(0, arm, cs[j], w)) for j in i])
            rec = lambda i, w: (np.mean([loss(f, "und", cs[j], w) - loss(f, arm, cs[j], w) for j in i])
                                / np.mean([loss(f, "und", cs[j], w) - loss(0, "und", cs[j], w) for j in i]))
            lo = boot_draws(lambda i: rec(i, None), len(cs), lv)[0]
            verdict = "not evaluated (harm unresolved)" if lower <= 0 else ("pass" if lo >= 0.5 else "fail")
            L.append(f"| {arm} | {len(cs)} | {summarise(ld, len(cs), lv)} | {summarise(gain, len(cs), lv)} | {summarise(mit, len(cs), lv)} | "
                     f"{summarise(rec, len(cs), lv)} | {verdict} |")
    parts = [g for g in (0, 3, 6, 9) if all(cm(key(f, a, g)) is not None for f in (0, 10) for a in ("und", "d1", "d1w", "d1t", "d1i"))]
    if parts:
        L += ["", f"## D1 split into its three changes (post-hoc diagnostic; clock starts {parts}; point means, no intervals at {len(parts)} draws)", "",
              "| arm | change | loss, no attack | loss, fill 10% | excess from the fill | benign packets refused by collision, fill 10% |",
              "|---|---|---|---|---|---|"]
        for arm, what in (("und", "shipped design"), ("d1w", "no wrap window only"), ("d1t", "takeover refresh only"),
                          ("d1i", "packet-gap timestamp only"), ("d1", "all three")):
            l0 = np.mean([loss(0, arm, g) for g in parts])
            l10 = np.mean([loss(10, arm, g) for g in parts])
            col = np.mean([np.mean(np.load(G5 / key(10, arm, g))["outcome"] == 3) for g in parts])
            L.append(f"| {arm} | {what} | {l0:+.4f} | {l10:+.4f} | {l10 - l0:+.4f} | {col:.2%} |")
    L += ["", "## Reading", "",
          "The pre-registered decision rules are applied to the recovery column only. A defence's benign gain (no-attack column) is shown "
          "apart from its mitigation so that a fix which helps benign traffic is not mistaken for attack mitigation. The attacker is the "
          "analytical holder abstraction; the emulator-to-switch validation of every defence remains owed."]
    (ROOT / "docs/results_g5_peerrush.md").write_text("\n".join(L) + "\n")
    print("\n".join(L))


if __name__ == "__main__":
    main()
