"""G6 addendum 4 -> docs/results_g6_adaptive.md (exploratory): leaked-key-bits arm and rekey arm against D4/D5, primary MAWI day.

Leak arm: share of the 20 `vul` victims downgraded when the attacker holds the victim's table-A slot and m distinct members of a c-slot candidate
set for its table-B slot. Prediction (pre-registered): S0 + (1 - S0) m / c, S0 = the control (table A held only). Rekey arm: change in the
downgraded-packet share (percentage points) when table B's hash is redrawn every T seconds, against D5 with no rotation, no attack; M1 limit 0.5 pp.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np

from dgrade.flowstats import FlowIndex, downgraded_flows

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "results/g2"
CELLS = [("ctl", 0, 0), ("c1m1", 1, 1), ("c2m2", 2, 2), ("c2m1", 2, 1), ("c8m8", 8, 8), ("c8m4", 8, 4), ("c64m64", 64, 64), ("c64m32", 64, 32)]


def ci(v: np.ndarray, lvl: float = 95.0, n: int = 4000) -> tuple[float, float]:
    b = [np.random.default_rng(i).choice(v, len(v)).mean() for i in range(n)]
    return float(np.percentile(b, (100 - lvl) / 2)), float(np.percentile(b, 100 - (100 - lvl) / 2))


def main() -> None:
    idx = FlowIndex(np.load(OUT / "targeted_prep_p.npz")["code"])
    L = ["# G6 addendum 4: leaked key bits and rekeying against D4/D5 (exploratory)", "",
         ("Generated by `scripts/g6_adaptive_report.py`. Primary MAWI day, oracle gate, 10 draws (clock starts), D4 (idle placement, shipped clock). "
          "The attacker is *given* the victim's table-A slot and a candidate set for its table-B slot; no probing procedure is modelled."), "",
         "## Leak arm", "",
         "| cell | candidates c | informed holders m | holders per victim | draws | victims downgraded [95% CI] | prediction S0 + (1 − S0)·m/c | deviation | attacker packets (mean) |",
         "|---|---|---|---|---|---|---|---|---|"]
    res: dict[str, np.ndarray] = {}
    pk: dict[str, float] = {}
    for cell, c, m in CELLS:
        vals, pks = [], []
        for g in range(10):
            p = OUT / f"g6l_p_vul_{cell}_at{g}.npz"
            if not p.exists():
                continue
            try:
                z = np.load(p)
                vals.append(downgraded_flows(z["benign_outcome"], idx)[z["victim_flow"]].mean())
                pks.append(float(z["n_attacker_packets"]))
            except (EOFError, ValueError, OSError):
                continue
        if vals:
            res[cell] = np.array(vals)
            pk[cell] = float(np.mean(pks))
    s0 = float(res["ctl"].mean()) if "ctl" in res else float("nan")
    falsified = []
    for cell, c, m in CELLS:
        if cell not in res:
            continue
        v = res[cell]
        lo, hi = ci(v)
        pred = s0 + (1 - s0) * (m / c) if c else s0
        dev = float(v.mean()) - pred
        if c and m == c and lo < 0.90:
            falsified.append(f"{cell}: lower bound {lo:.0%} < 90%")
        if abs(dev) > 0.15:
            falsified.append(f"{cell}: deviation {dev:+.2f} beyond ±0.15")
        L.append(f"| {cell} | {c or '-'} | {m} | {m + 1} | {len(v)} | {v.mean():.0%} [{lo:.0%}, {hi:.0%}] | {pred:.0%} | {dev:+.2f} | {pk[cell]:,.0f} |")
    L += ["", f"Control (table A held only): {s0:.0%} of victims downgraded, the floor from benign occupancy of table B.", ""]
    full = [float(res[c].mean()) for c, _cc, mm in CELLS if c in res and _cc and mm == _cc]
    if full:
        L += [f"With every candidate held (m = c) {min(full):.0%} to {max(full):.0%} of victims are downgraded, not 100%: the closed form over-predicts full-knowledge success "
              "by about 0.11 to 0.15 (cause not investigated; the m < c cells follow the m/c scaling more closely).", ""]
    L.append("Pre-registered falsification: " + ("**triggered** (" + "; ".join(falsified) + ")." if falsified else "not triggered (every m = c cell has a lower bound of at least 90%, and no cell departs from the closed form by more than 0.15)."))

    L += ["", "## Rekey arm (no attack)", "",
          "| rekey period T | draws | change in downgraded-packet share vs D5 without rotation (pp) [95% CI] | M1 (upper bound at most 0.5 pp) |", "|---|---|---|---|"]
    for T in (5, 10, 30, 60):
        d = []
        for g in range(10):
            a, b = OUT / f"a_p_oracle_crc_at{g}_p_d5r{T}.npz", OUT / f"a_p_oracle_crc_at{g}_p_d5.npz"
            if a.exists() and b.exists():
                try:
                    sa = downgraded_flows(np.load(a)["outcome"], idx)[idx.code].mean()
                    sb = downgraded_flows(np.load(b)["outcome"], idx)[idx.code].mean()
                    d.append((sa - sb) * 100)
                except (EOFError, ValueError, OSError):
                    continue
        if len(d) >= 3:
            d = np.array(d)
            lo, hi = ci(d)
            L.append(f"| {T} s | {len(d)} | {d.mean():+.2f} [{lo:+.2f}, {hi:+.2f}] | {'pass' if hi <= 0.5 else 'fail'} |")
    L += ["", "Reading. Under full knowledge of both placements an attacker needs two holders per victim; with a secret second hash the holders per victim needed "
          "rise with the residual uncertainty c, roughly one informed holder per candidate for a certain downgrade. Rekeying restarts every flow resident in table B, "
          "so its benign cost is large at short periods (table above). How fast a static key could be learned is not simulated here: an assumed one bit per refusal "
          "probe gives about 11 probes for a small keyed polynomial space and about 15 per victim for a full linear key (`docs/lit/adaptive_arms_design.md`, "
          "hand-derived), which puts learning time at seconds; a rekey period that beats that would violate the benign-cost limit. Not modelled: probe crafting, "
          "moving victims, adaptive holders, hardware cost of rotation. Emulator abstraction, one day, 10 draws."]
    (ROOT / "docs/results_g6_adaptive.md").write_text("\n".join(L) + "\n")
    print("\n".join(L))


if __name__ == "__main__":
    main()
