"""Pre-registered check: does the shipped flow-size model admit the holder packet pattern? -> docs/results_g6_gate_check.md"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
from g2_mawi import ART

from dgrade.inject import build_fill
from dgrade.netbeacon import load_tables
from dgrade.netbeacon_sim import TableModels

atk = build_fill(0.01, "k0", 65536, 20 * 10**9, np.random.default_rng(0))
m = TableModels(load_tables(ART))
first = np.zeros(len(atk.pk), bool)
first[np.unique(atk.flow, return_index=True)[1]] = True
fs, pc = m.flow_size(atk.pk), m.pkt_codes(atk.pk)
codes, counts = np.unique(pc, return_counts=True)
L = ["# Check: the shipped flow-size model admits the holder pattern", "",
     ("Generated by `scripts/g6_gate_check.py`. Holder packets are 60-byte TCP packets (TTL 64, window 1024, data offset 5) from `build_fill`. "
      "The shipped flow-size model (a long flow is one with a score above 50) is applied to the holder packets."), "",
     f"- Holder flows examined: {int(first.sum())}; packets: {len(atk.pk):,}.",
     f"- Flow-size score of the first packet: mean {fs[first].mean():.1f}; share above 50 (predicted long): {(fs[first] > 50).mean():.0%}.",
     f"- Share of all holder packets scored above 50: {(fs > 50).mean():.0%}.",
     f"- Per-packet verdict codes on holder packets (code: packets): {dict(zip(codes.tolist(), counts.tolist(), strict=True))}.", "",
     ("The emulator forces holders long and gives them per-packet code 1 (`g2b_mawi.py`); for this header pattern the shipped model agrees on both. "
      "Holders stay below 2,000 packets, and their phase verdicts are evaluated with the shipped tables like any other flow. "
      "This checks one header pattern, not every packet an attacker could send.")]
(ROOT / "docs/results_g6_gate_check.md").write_text("\n".join(L) + "\n")
print("\n".join(L))
