"""G6 check 2: are the two candidate slots of D4 independent on the real tuple sets? -> docs/results_g6_hash_check.md

Over unique tuples, compares the joint collision rate P(A and B) with P(A) * P(B), where A = slot in table A (shipped CRC32) and B = slot in
table B (a second irreducible-polynomial CRC, seed 7919, or tabulation hashing). Ratio within [0.8, 1.25] passes (docs/preregistration.md, G6).
"""

from __future__ import annotations

from pathlib import Path

import numpy as np

from dgrade.netbeacon_sim import hash_unique, tuple_table

ROOT = Path(__file__).resolve().parents[1]


def pairs(keys: np.ndarray) -> float:
    _, c = np.unique(keys, return_counts=True)
    return float(np.sum(c * (c - 1) // 2))


def ratio(a: np.ndarray, b: np.ndarray) -> tuple[float, float, float, float]:
    n = len(a)
    tot = n * (n - 1) / 2
    pa, pb, pab = pairs(a) / tot, pairs(b) / tot, pairs(a.astype(np.int64) * (int(b.max()) + 1) + b) / tot
    return pa, pb, pab, pab / (pa * pb)


def main() -> None:
    sets = {}
    z = np.load(ROOT / "results/g1/stream.npz")["pk"]
    sets["PeerRush (4,096 + 4,096 slots)"] = (tuple_table(z["src_ip"], z["dst_ip"], z["src_port"], z["dst_port"], z["proto"])[0], 4096)
    for d, name in (("p", "MAWI 2022-09-14"), ("r", "MAWI 2023-03-15")):
        sets[f"{name} (32,768 + 32,768 slots)"] = (np.load(ROOT / f"results/g2/prep_{d}.npz")["uniq"], 32768)
    L = ["# G6 check 2: independence of the two candidate slots", "",
         "Generated by `scripts/g6_hash_check.py`. Over unique tuples: joint collision rate against the product of the marginals (ratio 1 = independent); pass if within [0.8, 1.25].", "",
         "| tuple set | unique tuples | hash B | P(A) | P(B) | P(A and B) | ratio | check |", "|---|---|---|---|---|---|---|---|"]
    for name, (uniq, half) in sets.items():
        a = (hash_unique(uniq, "crc", None) % half).astype(np.int64)
        for kind, seed, label in (("polyirr", 7919, "irreducible CRC (seed 7919)"), ("tab", 7919, "tabulation (reference)")):
            b = (hash_unique(uniq, kind, seed) % half).astype(np.int64)
            pa, pb, pab, r = ratio(a, b)
            L.append(f"| {name} | {len(uniq):,} | {label} | {pa:.3e} | {pb:.3e} | {pab:.3e} | {r:.3f} | {'pass' if 0.8 <= r <= 1.25 else 'FAIL'} |")
    (ROOT / "docs/results_g6_hash_check.md").write_text("\n".join(L) + "\n")
    print("\n".join(L))


if __name__ == "__main__":
    main()
