"""G6 on MAWI: two-choice tables D4/D5/D4s -> docs/results_g6_mawi.md (docs/preregistration.md, G6 entry).

Loss = benign flows downgraded (oracle gate). For arm X at draw g: E_X = loss(X, fill) - loss(X, no attack); benign gain G_X = loss(und, 0) - loss(X, 0);
mitigation = E_und - E_X; recovery R = 1 - mean(E_X) / mean(E_und), paired by draw (clock start). Collision-refusal share = share of benign packets
refused by an active incumbent (outcome FALLBACK_COLLISION). Intervals: percentile bootstrap over draws; a paired sign-flip test decides
R > 0.5. Matched refusal: the nominal load at which D4's collision-refusal share equals the undefended share at f = 10% (interpolated).
"""

from __future__ import annotations

from pathlib import Path

import numpy as np

from dgrade.flowstats import FlowIndex, downgraded_flows
from dgrade.netbeacon_sim import FALLBACK_COLLISION

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "results/g2"
DAYS = {"p": "2022-09-14 (primary)", "r": "2023-03-15 (replication)"}
N_BOOT = 4000
LVL_HOLM = 97.5          # two-sided percentile bounds at the Holm-conservative level (m = 4)


def main() -> None:
    idx = {d: FlowIndex(np.load(OUT / f"targeted_prep_{d}.npz")["code"]) for d in DAYS}
    cache: dict[str, np.ndarray] = {}

    def load(name: str, key: str) -> np.ndarray | None:
        if not (OUT / name).exists():
            return None
        if name not in cache:
            try:
                cache[name] = np.load(OUT / name)[key]
            except (EOFError, ValueError, OSError):        # a file still being written by a running job
                return None
        return cache[name]

    def nm(kind: str, d: str, g: int, f: int = 0, arm: str = "", n: int = 65536) -> str:
        suf = (f"_p_{arm}" if arm else "") + (f"_n{n}" if n != 65536 else "")
        return f"b_{d}_oracle_b0l_{f}_at{g}{suf}.npz" if kind == "b" else f"a_{d}_oracle_crc_at{g}{suf}.npz"

    memo: dict[tuple, float | None] = {}

    def stats(d: str, g: int, f: int, arm: str, n: int) -> tuple[float, float] | None:
        """(benign flows downgraded, collision-refusal share) of one run, computed once."""
        k = (d, g, f, arm, n)
        if k not in memo:
            name = nm("b" if f else "a", d, g, f, arm, n)
            o = load(name, "benign_outcome" if f else "outcome")
            memo[k] = None if o is None else (float(downgraded_flows(o, idx[d]).sum()), float(np.mean(o == FALLBACK_COLLISION)))
            cache.pop(name, None)                       # free the large outcome array
        return memo[k]

    def flows(d: str, g: int, f: int, arm: str, n: int = 65536) -> float | None:
        s = stats(d, g, f, arm, n)
        return None if s is None else s[0]

    def refusal(d: str, g: int, f: int, arm: str, n: int = 65536) -> float | None:
        s = stats(d, g, f, arm, n)
        return None if s is None else s[1]

    def series(d: str, f: int, arm: str, clocks, n: int = 65536):
        """Paired arrays over draws for which every needed run exists: E_und, E_arm, G, refusal shares."""
        rows = []
        for g in clocks:
            v = [flows(d, g, f, "", n), flows(d, g, 0, "", n), flows(d, g, f, arm, n), flows(d, g, 0, arm, n)]
            r = [refusal(d, g, f, "", n), refusal(d, g, f, arm, n), refusal(d, g, 0, "", n), refusal(d, g, 0, arm, n)]
            if None not in v and None not in r:
                rows.append((v[0] - v[1], v[2] - v[3], v[1] - v[3], *r, v[2] - v[1]))
        return np.array(rows, float).reshape(-1, 8)

    def rec_ci(a: np.ndarray, lvl: float = LVL_HOLM) -> tuple[float, float, float]:
        rng = np.random.default_rng(0)
        i = rng.integers(0, len(a), (N_BOOT, len(a)))
        r = 1 - a[i, 1].mean(1) / np.maximum(a[i, 0].mean(1), 1e-9)
        lo, hi = (100 - lvl) / 2, 100 - (100 - lvl) / 2
        return 1 - a[:, 1].mean() / max(a[:, 0].mean(), 1e-9), float(np.percentile(r, lo)), float(np.percentile(r, hi))

    def signflip_p(d: np.ndarray, n: int = 20000) -> float:
        """One-sided p for mean(d) > 0 by sign flips."""
        rng = np.random.default_rng(1)
        obs = d.mean()
        s = rng.choice([-1.0, 1.0], (n, len(d)))
        return float((np.sum((s * d).mean(1) >= obs - 1e-12) + 1) / (n + 1))

    L = ["# G6 on MAWI: capacity-matched two-choice tables (D4, D5, D4s)", "",
         ("Generated by `scripts/g6_mawi_report.py` from `results/g2/`. Oracle gate, random-slot (B0-L) fill at 4 packets/s, f = nominal holder load per "
          "slot. Loss = benign flows downgraded. **Recovery** R = 1 − mean(E_arm) / mean(E_und) with E measured against each arm's own no-attack run, "
          "paired by draw; **benign gain** = undefended no-attack minus the arm's no-attack; **G4a-style** = the ratio against the undefended no-attack "
          "run (shown for continuity, decides nothing). Intervals are percentile bootstrap over draws at the Holm-conservative level "
          f"({LVL_HOLM}% two-sided). Collision-refusal share = benign packets refused by an active incumbent."), ""]

    for d, dn in DAYS.items():
        L += [f"## {dn}", "",
              ("| f | arm | draws | E_und (flows) | E_arm | benign gain | R [CI] | R > 0.5 (sign-flip p) | G4a-style | "
               "refusal share: und, arm (no attack) | refusal share: und, arm (fill) |"), "|---|---|---|---|---|---|---|---|---|---|---|"]
        for f in (10, 25, 50):
            for arm in ("d4", "d5", "d4s"):
                a = series(d, f, arm, range(30))
                if not len(a):
                    continue
                r, lo, hi = rec_ci(a)
                p = signflip_p(0.5 * a[:, 0] - a[:, 1])
                g4 = 1 - a[:, 7].mean() / max(a[:, 0].mean(), 1e-9)      # defended attack against the undefended no-attack run
                L.append(f"| {f}% | {arm} | {len(a)} | {a[:, 0].mean():,.0f} | {a[:, 1].mean():,.0f} | {a[:, 2].mean():+,.0f} | "
                         f"{r:+.2f} [{lo:+.2f}, {hi:+.2f}] | {p:.4f} | {g4:+.2f} | {a[:, 5].mean():.2%}, {a[:, 6].mean():.2%} | "
                         f"{a[:, 3].mean():.2%}, {a[:, 4].mean():.2%} |")
        L.append("")

    # H-D5 equivalence and the same-hash control (primary day, f = 10%)
    a4, a5, as_ = (series("p", 10, x, range(30)) for x in ("d4", "d5", "d4s"))
    L += ["## H-D5 equivalence and the D4s control (primary day, f = 10%)", ""]
    n = min(len(a4), len(a5))
    if n:
        rng = np.random.default_rng(2)
        i = rng.integers(0, n, (N_BOOT, n))
        ratio = a5[:n, 1][i].mean(1) / np.maximum(a4[:n, 1][i].mean(1), 1e-9)
        lo, hi = np.percentile(ratio, [5, 95])
        L.append(f"E_D5 / E_D4 = {a5[:n, 1].mean() / max(a4[:n, 1].mean(), 1e-9):.3f}, 90% interval [{lo:.3f}, {hi:.3f}] over {n} draws; "
                 f"pre-registered equivalence bounds [0.9, 1.1]: **{'inside' if lo >= 0.9 and hi <= 1.1 else 'not inside'}**.")
    else:
        L.append("D5 not run.")
    m = min(len(a4), len(as_))
    if m:
        rng = np.random.default_rng(3)
        i = rng.integers(0, m, (N_BOOT, m))
        dr = (as_[:m, 1][i].mean(1) - a4[:m, 1][i].mean(1)) / np.maximum(a4[:m, 0][i].mean(1), 1e-9)
        lo, hi = np.percentile(dr, [2.5, 97.5])
        L += ["", f"D4 against D4s (2-way set-associative): (E_D4s − E_D4) / E_und = {(as_[:m, 1].mean() - a4[:m, 1].mean()) / max(a4[:m, 0].mean(), 1e-9):+.3f} "
              f"[{lo:+.3f}, {hi:+.3f}] over {m} draws. An interval that excludes zero means independent hashes matter; if it includes zero, "
              "the claim is two-choice at equal capacity, not independent hashes."]
    else:
        L += ["", "D4s not run."]

    # M3 matched refusal
    L += ["", "## M3: matched-refusal attacker cost (primary day)", ""]
    pts = {}
    for arm in ("", "d4"):
        for f in (10, 25, 50):
            vals = [refusal("p", g, f, arm) for g in range(30)]
            vals = [v for v in vals if v is not None]
            if vals:
                pts[(arm, f)] = np.array(vals)
    if ("", 10) in pts and all(("d4", f) in pts for f in (10, 25, 50)):
        target = pts[("", 10)].mean()
        fs = np.array([10, 25, 50], float)

        def match(rng_: np.random.Generator | None) -> float:
            y = np.array([(rng_.choice(pts[("d4", f)], len(pts[("d4", f)])).mean() if rng_ else pts[("d4", f)].mean()) for f in (10, 25, 50)])
            t = rng_.choice(pts[("", 10)], len(pts[("", 10)])).mean() if rng_ else target
            return float(np.interp(t, y, fs)) if y[0] <= t <= y[-1] else (float("nan") if t > y[-1] else float(fs[0]))
        point = match(None)
        rng = np.random.default_rng(4)
        bs = np.array([match(rng) for _ in range(2000)])
        bs = bs[np.isfinite(bs)]
        lo = float(np.percentile(bs, 2.5)) if len(bs) else float("nan")
        L.append(f"Undefended collision-refusal share at f = 10%: {target:.2%}. D4 shares at f = 10, 25, 50%: "
                 + ", ".join(f"{pts[('d4', f)].mean():.2%}" for f in (10, 25, 50)) + ". "
                 f"Matched nominal load ≈ {point:.0f}% ⇒ budget multiple ≈ {point / 10:.1f}× (lower 95% bound {lo / 10:.1f}×; pass if at least 2×).")
    else:
        L.append("Not enough D4 arms finished to interpolate.")

    # load sweep
    L += ["", "## Load sweep (primary day, f = 10%, clocks 0 to 9)", "",
          "| table slots | undefended no-attack refusal share (load proxy) | draws | E_und (flows) | E_D4 | benign gain | R [CI] |", "|---|---|---|---|---|---|---|"]
    for n_ in (65536, 32768, 16384, 8192):
        a = series("p", 10, "d4", range(10), n_)
        if not len(a):
            continue
        r, lo, hi = rec_ci(a)
        L.append(f"| {n_:,} | {a[:, 5].mean():.2%} | {len(a)} | {a[:, 0].mean():,.0f} | {a[:, 1].mean():,.0f} | {a[:, 2].mean():+,.0f} | "
                 f"{r:+.2f} [{lo:+.2f}, {hi:+.2f}] |")
    L += ["", "Reading: emulator results with an analytical holder abstraction. Deployability on Tofino-1 is unverified "
          "(`docs/lit/overnight_p4_feasibility.md`). The load-sweep row where R crosses zero bounds the claim."]
    (ROOT / "docs/results_g6_mawi.md").write_text("\n".join(L) + "\n")
    print("\n".join(L))


if __name__ == "__main__":
    main()
