"""G6 targeted pilot -> docs/results_g6_targeted.md (exploratory; docs/preregistration.md, G6 addendum).

Share of the 20 victim flows downgraded (primary day, oracle gate) when holders sit on the victims' slots, by design and attacker knowledge.
Draws are clock starts on one capture; intervals are 95% percentile bootstrap over draws. No-attack reference: the same design's no-attack run.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np

from dgrade.flowstats import FlowIndex, downgraded_flows

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "results/g2"
ARMS = [("und1", "one table, K1: 1 holder per victim on its slot", "", 1),
        ("d4k1", "D4, both hashes known: 1 holder per victim (candidates = the victim's two slots)", "d4", 1),
        ("d4k2", "D4, both hashes known: 2 holders per victim", "d4", 2),
        ("d5k2", "D5 (secret second hash): 2 holders per victim, table A known, table B random", "d5", 2)]


def main() -> None:
    idx = FlowIndex(np.load(OUT / "targeted_prep_p.npz")["code"])
    L = ["# G6 targeted pilot: known-hash holders against D4 and D5 (exploratory)", "",
         ("Generated by `scripts/g6_targeted_report.py`. Primary MAWI day, oracle gate, 20 victims per set (`top`: the 20 largest benign long flows; `vul`: the "
          "20 largest that never reach 2,048 packets), holders start 0.5 s before the victim's first packet. Analytical attacker: it is *given* the slots it "
          "needs (no hash search, no probing model, no adaptive behaviour). Share of victims downgraded, mean over draws (clock starts) with a 95% "
          "percentile bootstrap interval; the no-attack column is the same design without holders."), "",
         "| victim set | arm | holders per victim | draws | victims downgraded | no attack |", "|---|---|---|---|---|---|"]
    for v in ("vul", "top"):
        for arm, desc, dfn, per in ARMS:
            vals, refs = [], []
            for g in range(10):
                p = OUT / f"g6t_p_{v}_{arm}_at{g}.npz"
                base = OUT / (f"a_p_oracle_crc_at{g}" + (f"_p_{dfn}" if dfn else "") + ".npz")
                if not (p.exists() and base.exists()):
                    continue
                try:
                    z = np.load(p)
                    vf = z["victim_flow"]
                    vals.append(downgraded_flows(z["benign_outcome"], idx)[vf].mean())
                    refs.append(downgraded_flows(np.load(base)["outcome"], idx)[vf].mean())
                except (EOFError, ValueError, OSError):
                    continue
            if not vals:
                continue
            a = np.array(vals)
            bs = [np.random.default_rng(i).choice(a, len(a)).mean() for i in range(2000)]
            L.append(f"| {v} | {desc} | {per} | {len(a)} | {a.mean():.0%} [{np.percentile(bs, 2.5):.0%}, {np.percentile(bs, 97.5):.0%}] | {np.mean(refs):.0%} |")
    L += ["", "Reading: with both hashes known, D4 asks the attacker for two holders per victim instead of one (a constant factor); with a secret second hash "
          "the attacker's second holder finds the victim's table-B slot only by chance. The pilot does not model probing that learns the second hash "
          "(about 20 to 35 refusal probes for a small keyed space, `docs/lit/overnight_adversary_model.md`), adaptive holders, or the both-ways-owned "
          "race of a real recirculation path. It supports no claim about a hash-knowing adversary beyond the constant factor."]
    (ROOT / "docs/results_g6_targeted.md").write_text("\n".join(L) + "\n")
    print("\n".join(L))


if __name__ == "__main__":
    main()
