"""G7-0 diagnosis (post-hoc; not a rescue): in-sample versus held-out macro-F1 of the retrained models -> docs/results_g7_diagnosis.md"""
import json, sys, numpy as np, joblib
from pathlib import Path
sys.path.insert(0,"scripts"); sys.path.insert(0,"src")
from iscx_models import f1, class_of, NC
from dgrade.netbeacon_sim import NetBeaconSim, flow_ids, NEW_OWNER
z=np.load("results/g7/stream.npz"); pk,cap,cls=z["pk"],z["cap"],z["cls"].astype(np.int64)
caps=json.load(open("results/g7/captures.json")); g=np.array([c["group"] for c in caps["captures"]])
fid=flow_ids(pk,1<<62); nf=fid.max()+1; first=np.full(nf,len(pk)); np.minimum.at(first,fid,np.arange(len(pk)))
flen=np.bincount(fid,minlength=nf); fcls=cls[first]; fgrp=g[cap[first]]
fold=np.zeros(nf,dtype=np.int8)
for c in range(NC):
    gs=sorted(set(fgrp[fcls==c]))
    if len(gs)>1:
        for i,x in enumerate(gs): fold[(fcls==c)&(fgrp==x)]=i%2
    else:
        m=fcls==c; t=pk["ts_ns"][first][m]; fold[m]=(t>=np.median(t)).astype(np.int8)
fp=fold[fid]; longp=(flen>50)[fid]
rows=[]
for f in (0,1):
    m=joblib.load(f"results/g7/models_fold{f}.joblib")
    out=NetBeaconSim(models=m,clock_offset_ns=300*(1<<20)).run(pk,isolate=fid)
    res=out["result"]; fb=m.pkt_codes(pk)-1
    for name,sel in (("held-out (fold %d)"%f, fp==f),("in-sample (fold %d)"%(1-f), fp==1-f)):
        s=sel&longp
        rows.append((f, name, f1(cls[s],class_of(res)[s]), f1(cls[s],fb[s])))
    s=(fp==f)&longp
    cm=np.bincount(cls[s]*(NC+1)+np.where(class_of(res)[s]<0,NC,class_of(res)[s]),minlength=NC*(NC+1)).reshape(NC,NC+1)


L=["# G7-0 diagnosis: why the full-state path loses to the fallback on held-out sessions (post-hoc, not a rescue)","",
   "Generated by `scripts/iscx_diag.py`. Long flows (more than 50 packets), packet-level macro-F1. Model k was trained on the other fold; 'in-sample' means the flows it was trained on.","",
   "| model | evaluated on | full model | per-packet fallback |","|---|---|---|---|"]
for f,name,a,b in rows: L.append(f"| trained excluding fold {f} | {name} | {a:.3f} | {b:.3f} |")
L+=["","In-sample the full-state path beats the fallback (the pipeline works: features, phase trees, emulator). On held-out session groups it collapses, while the per-packet tree, which uses TTL, ToS and window, generalises better. With 29 VPN-only captures in 16 session groups the flow-statistics trees memorise sessions. The pre-registered G7-0 rule (gap below 0.03 kills the workload) stands; the models were not tuned after seeing this. Any model change would be a new dated, post-hoc addendum."]
Path("docs/results_g7_diagnosis.md").write_text("\n".join(L)+"\n"); print("\n".join(L))
