"""Traffic summary of the pre-registered MAWI slices -> docs/results_g2_traffic.md (every number computed here).

Detector inputs (docs/preregistration.md, G2): benign new-flow rate and byte rate in 1-second bins.
A flow is "new" at its first packet inside the slice, so the first seconds are inflated by flows that
started before the slice; the warm-up bins are shown separately.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np

from dgrade.netbeacon_sim import flow_ids
from dgrade.pcap import read_pcap

ROOT = Path(__file__).resolve().parents[1]
DAYS = {"2022-09-14 (primary)": "202209141400", "2023-03-15 (replication)": "202303151400"}
WARM = 5


def main() -> None:
    L = ["# G2 benign traffic: MAWI samplepoint F, first 120 s of the pre-registered days", "",
         ("Generated by `scripts/mawi_stats.py`. Headers only (96-byte capture length); addresses scrambled by the archive. "
         "Parser filter as for PeerRush (IPv4 without options or fragments, TCP or UDP)."), ""]
    rows = []
    for name, d in DAYS.items():
        pk, st = read_pcap(ROOT / f"data/raw/mawi/{d}_120s.pcap", sort_by_time=True)
        t = (pk["ts_ns"] - pk["ts_ns"].min()) / 1e9
        sec = t.astype(int)
        fid = flow_ids(pk, 1 << 62)
        nf = int(fid.max()) + 1
        first = np.full(nf, -1, dtype=np.int64)
        first[fid[::-1]] = np.arange(len(fid))[::-1]
        newf = np.bincount(sec[first], minlength=120)
        byt = np.bincount(sec, weights=pk["total_len"].astype(np.float64), minlength=120) * 8 / 1e6      # Mb/s
        pps = np.bincount(sec, minlength=120)
        src24 = pk["src_ip"][first] >> 8
        key = sec[first].astype(np.int64) * (1 << 24) + src24
        _uk, cnt = np.unique(key, return_counts=True)
        per24_p99 = float(np.percentile(cnt, 99))
        rows.append((name, st, len(pk), nf, newf, byt, pps, per24_p99, float(np.mean(pk["proto"] == 6))))
    L += ["## Slice contents", "", ("| day | records in slice | kept after filter | dropped: not IPv4 | dropped: fragments | "
          "dropped: not TCP/UDP | out-of-order packets | TCP share | flows (bidirectional 5-tuples) |"), "|---|---|---|---|---|---|---|---|---|"]
    for name, st, n, nf, *_rest, tcp in rows:
        L.append(f"| {name} | {st['records']:,} | {n:,} | {st['not_ipv4']:,} | {st['fragment']:,} | {st['not_tcp_udp']:,} | "
                 f"{st['reordered']:,} | {tcp:.1%} | {nf:,} |")
    L += ["", "## Load and detector inputs (1-second bins)", "",
          f"Bins 0 to {WARM - 1} are warm-up: every flow already in progress at the slice start counts as new there.", "",
          ("| day | packets/s (mean) | new flows/s: mean (bins ≥ 5) | new flows/s: p99, all 120 bins | new flows/s: p99, bins ≥ 5 | "
          "max new flows/s (bin index) | Mb/s: mean | Mb/s: p99, all bins | new flows per /24 per second: p99 |"),
          "|---|---|---|---|---|---|---|---|---|"]
    for name, _st, _n, _nf, newf, byt, pps, p24, _tcp in rows:
        mx = int(np.argmax(newf))
        L.append(f"| {name} | {pps.mean():,.0f} | {newf[WARM:].mean():,.0f} | {np.percentile(newf, 99):,.0f} | "
                 f"{np.percentile(newf[WARM:], 99):,.0f} | {newf.max():,} (bin {mx}) | {byt.mean():,.0f} | "
                 f"{np.percentile(byt, 99):,.0f} | {p24:,.0f} |")
    L += ["", "First ten bins of new flows per second, per day:", ""]
    for name, _st, _n, _nf, newf, *_ in rows:
        L.append(f"- {name}: {', '.join(f'{int(v):,}' for v in newf[:10])}")
    (ROOT / "docs/results_g2_traffic.md").write_text("\n".join(L) + "\n")
    print("\n".join(L))


if __name__ == "__main__":
    main()
