"""How often does NetBeacon's full-model verdict agree with its per-packet fallback verdict? -> docs/results_v2_agreement.md

PeerRush, isolated reference run at clock grid 0 (every flow has a slot, so the full model runs). The fallback is the shipped
Pkt_Tree applied to every packet. Retrospective agreement over a whole flow is an upper bound on what a rule that only sees
phase-packet verdicts so far can identify; the emulator evaluates the predictive rule.
"""

from __future__ import annotations

import itertools
from pathlib import Path

import numpy as np

from dgrade.flowstats import FlowIndex
from dgrade.netbeacon import load_tables
from dgrade.netbeacon_sim import TableModels, flow_ids

ROOT = Path(__file__).resolve().parents[1]


def cls(r: np.ndarray) -> np.ndarray:
    r = r.astype(np.int64)
    return np.where(r == 0, -1, (r - 1) % 50)


def macro_f1(truth, pred, perm) -> float:
    p = np.where(pred < 0, 3, np.asarray(perm)[np.clip(pred, 0, 2)])
    cm = np.bincount(truth.astype(int) * 4 + p, minlength=12).reshape(3, 4)
    f = []
    for c in range(3):
        tp = cm[c, c]
        fp, fn = cm[:, c].sum() - tp, cm[c].sum() - tp
        f.append(0 if tp == 0 else 2 * tp / (2 * tp + fp + fn))
    return float(np.mean(f))


def main() -> None:
    z = np.load(ROOT / "results/g1/stream.npz")
    pk, lab = z["pk"], z["lab"]
    full = cls(np.load(ROOT / "results/g1/g1b_iso_at0.npz")["result"])
    fb = cls(TableModels(load_tables(ROOT / "third_party/NetBeacon")).pkt_codes(pk))
    idx = FlowIndex(flow_ids(pk, 1 << 62))
    perm = max(itertools.permutations(range(3)), key=lambda p: macro_f1(lab, full, p))
    base = macro_f1(lab, full, perm)
    n = idx.n_pkts
    agree = idx.per_flow_sum(full == fb) / n
    long_ = n > 50
    L = ["# Full-model against fallback verdict agreement on PeerRush", "",
         ("Generated by `scripts/v2_agreement.py`. Packet-level macro-F1 against the capture labels, isolated reference run "
          "(clock grid 0). The fallback is the shipped per-packet tree applied to every packet."), "",
         (f"- Macro-F1, full model: {base:.4f}. Macro-F1, fallback only: {macro_f1(lab, fb, perm):.4f}. "
         f"Packets where the two verdicts agree: {np.mean(full == fb):.1%}."), "",
         ("Replacing the full-model verdicts of the flows whose verdicts agree with the fallback on at least the given share of their packets "
         "by the fallback verdicts (the slot would not be needed):"), "",
         "| agreement threshold | share of all flows | share of long flows (> 50 packets) | share of packets | macro-F1 after replacement | change |",
         "|---|---|---|---|---|---|"]
    for thr in (1.0, 0.99, 0.95, 0.9):
        sel = agree >= thr
        mixed = np.where(sel[idx.code], fb, full)
        f1 = macro_f1(lab, mixed, perm)
        L.append(f"| ≥ {thr:.0%} | {sel.mean():.1%} | {(sel & long_).sum() / long_.sum():.1%} | {n[sel].sum() / n.sum():.1%} | "
                 f"{f1:.4f} | {f1 - base:+.4f} |")
    L += ["", ("Agreement over a whole flow is retrospective. Most agreeing flows are short (one or a few packets, where the two "
               "models trivially agree); the long-flow column is the relevant pool for slot eviction.")]
    (ROOT / "docs/results_v2_agreement.md").write_text("\n".join(L) + "\n")
    print("\n".join(L))


if __name__ == "__main__":
    main()
